using AstFirst;

namespace AstFirst.Tests.Runtime;

public class ArrayTypeSymbolTests
{
    private static readonly TypeSymbol Int = new("int");
    private static readonly TypeSymbol Animal = new("Animal");
    private static readonly TypeSymbol Dog = new("Dog", Animal);

    [Fact]
    public void Kind_IsArray()
    {
        var arr = new ArrayTypeSymbol(Int);
        Assert.Equal(TypeKind.Array, arr.Kind);
    }

    [Fact]
    public void Name_AutoGenerated()
    {
        var arr1 = new ArrayTypeSymbol(Int);
        var arr2 = new ArrayTypeSymbol(Int, 2);
        Assert.Equal("int[]", arr1.Name);
        Assert.Equal("int[,]", arr2.Name);
    }

    [Fact]
    public void Equals_SameElementAndRank_True()
    {
        var a1 = new ArrayTypeSymbol(Int);
        var a2 = new ArrayTypeSymbol(Int);
        Assert.Equal(a1, a2);
        Assert.Equal(a1.GetHashCode(), a2.GetHashCode());
    }

    [Fact]
    public void Equals_DifferentRank_False()
    {
        var a1 = new ArrayTypeSymbol(Int, 1);
        var a2 = new ArrayTypeSymbol(Int, 2);
        Assert.NotEqual(a1, a2);
    }

    [Fact]
    public void IsAssignableFrom_CovariantElement_True()
    {
        // Animal[] へ Dog[] を代入可 (配列共変性)
        var animalArr = new ArrayTypeSymbol(Animal);
        var dogArr = new ArrayTypeSymbol(Dog);
        Assert.True(animalArr.IsAssignableFrom(dogArr));
    }

    [Fact]
    public void IsAssignableFrom_DifferentRank_False()
    {
        var a1 = new ArrayTypeSymbol(Int, 1);
        var a2 = new ArrayTypeSymbol(Int, 2);
        Assert.False(a1.IsAssignableFrom(a2));
    }

    [Fact]
    public void IsAssignableFrom_NonArray_False()
    {
        var arr = new ArrayTypeSymbol(Int);
        Assert.False(arr.IsAssignableFrom(Int));
    }
}
