using AstFirst;

namespace AstFirst.Tests.Runtime;

public class FunctionTypeSymbolTests
{
    private static readonly TypeSymbol Int = new("int");
    private static readonly TypeSymbol Bool = new("bool");
    private static readonly TypeSymbol Animal = new("Animal");
    private static readonly TypeSymbol Dog = new("Dog", Animal);

    [Fact]
    public void Kind_IsFunction()
    {
        var f = new FunctionTypeSymbol(Int, new[] { Int });
        Assert.Equal(TypeKind.Function, f.Kind);
    }

    [Fact]
    public void Name_AutoGenerated()
    {
        var f = new FunctionTypeSymbol(Int, new[] { Int, Bool });
        Assert.Equal("(int, bool) => int", f.Name);
    }

    [Fact]
    public void Equals_SameSignature_True()
    {
        var f1 = new FunctionTypeSymbol(Int, new[] { Int, Bool });
        var f2 = new FunctionTypeSymbol(Int, new[] { Int, Bool });
        Assert.Equal(f1, f2);
        Assert.Equal(f1.GetHashCode(), f2.GetHashCode());
    }

    [Fact]
    public void Equals_DifferentSignature_False()
    {
        var f1 = new FunctionTypeSymbol(Int, new[] { Int });
        var f2 = new FunctionTypeSymbol(Int, new[] { Bool });
        Assert.NotEqual(f1, f2);
    }

    [Fact]
    public void IsAssignableFrom_SameSignature_True()
    {
        var f1 = new FunctionTypeSymbol(Int, new[] { Int });
        var f2 = new FunctionTypeSymbol(Int, new[] { Int });
        Assert.True(f1.IsAssignableFrom(f2));
    }

    [Fact]
    public void IsAssignableFrom_CovariantReturn_True()
    {
        // 戻り値共変: () => Animal へ () => Dog を代入可
        var toAnimal = new FunctionTypeSymbol(Animal, System.Array.Empty<TypeSymbol>());
        var fromDog = new FunctionTypeSymbol(Dog, System.Array.Empty<TypeSymbol>());
        Assert.True(toAnimal.IsAssignableFrom(fromDog));
    }

    [Fact]
    public void IsAssignableFrom_ContravariantParam_True()
    {
        // 引数反変: (Animal) => int へ (Dog) => int を代入可
        var toAnimalParam = new FunctionTypeSymbol(Int, new[] { Animal });
        var fromDogParam = new FunctionTypeSymbol(Int, new[] { Dog });
        Assert.True(toAnimalParam.IsAssignableFrom(fromDogParam));
    }

    [Fact]
    public void IsAssignableFrom_DifferentArity_False()
    {
        var f1 = new FunctionTypeSymbol(Int, new[] { Int });
        var f2 = new FunctionTypeSymbol(Int, new[] { Int, Int });
        Assert.False(f1.IsAssignableFrom(f2));
    }

    [Fact]
    public void IsAssignableFrom_NonFunction_False()
    {
        var f = new FunctionTypeSymbol(Int, new[] { Int });
        Assert.False(f.IsAssignableFrom(Int));
    }
}
