// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfManyTokens;

[Grammar]
[Skip(@"\s+")]
public abstract partial class TokenProgram : AstNode { }

public sealed partial class NilProgram : TokenProgram
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class Kw0 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw0", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw1 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw1", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw2 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw2", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw3 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw3", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw4 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw4", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw5 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw5", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw6 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw6", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw7 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw7", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw8 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw8", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw9 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw9", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw10 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw10", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw11 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw11", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw12 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw12", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw13 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw13", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw14 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw14", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw15 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw15", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw16 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw16", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw17 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw17", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw18 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw18", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw19 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw19", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw20 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw20", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw21 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw21", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw22 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw22", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw23 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw23", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw24 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw24", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw25 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw25", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw26 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw26", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw27 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw27", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw28 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw28", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw29 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw29", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw30 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw30", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw31 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw31", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw32 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw32", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw33 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw33", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw34 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw34", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw35 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw35", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw36 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw36", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw37 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw37", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw38 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw38", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw39 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw39", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw40 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw40", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw41 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw41", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw42 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw42", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw43 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw43", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw44 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw44", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw45 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw45", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw46 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw46", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw47 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw47", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw48 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw48", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw49 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw49", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw50 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw50", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw51 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw51", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw52 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw52", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw53 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw53", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw54 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw54", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw55 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw55", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw56 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw56", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw57 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw57", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw58 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw58", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw59 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw59", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw60 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw60", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw61 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw61", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw62 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw62", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw63 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw63", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw64 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw64", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw65 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw65", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw66 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw66", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw67 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw67", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw68 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw68", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw69 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw69", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw70 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw70", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw71 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw71", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw72 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw72", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw73 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw73", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw74 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw74", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw75 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw75", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw76 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw76", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw77 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw77", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw78 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw78", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw79 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw79", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw80 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw80", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw81 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw81", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw82 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw82", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw83 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw83", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw84 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw84", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw85 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw85", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw86 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw86", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw87 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw87", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw88 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw88", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw89 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw89", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw90 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw90", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw91 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw91", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw92 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw92", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw93 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw93", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw94 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw94", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw95 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw95", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw96 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw96", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw97 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw97", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw98 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw98", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class Kw99 : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"kw99", Priority = 1)] Token kw, TokenProgram rest) { }
}

public sealed partial class IdentNode : TokenProgram
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, TokenProgram rest) { }
}

