// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace CSharpParser;

[Grammar]
[Skip(@"(\s|//[^\n]*)+")]
public abstract partial class CSharpCompilationUnit : AstNode { }

public abstract partial class Type : AstNode { }

public sealed partial class IntType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"int", Priority = 1)] Token kw) { }
}

public sealed partial class StringType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"string", Priority = 1)] Token kw) { }
}

public sealed partial class BoolType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"bool", Priority = 1)] Token kw) { }
}

public sealed partial class DoubleType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"double", Priority = 1)] Token kw) { }
}

public sealed partial class FloatType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"float", Priority = 1)] Token kw) { }
}

public sealed partial class CharType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"char", Priority = 1)] Token kw) { }
}

public sealed partial class ByteType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"byte", Priority = 1)] Token kw) { }
}

public sealed partial class SbyteType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"sbyte", Priority = 1)] Token kw) { }
}

public sealed partial class ShortType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"short", Priority = 1)] Token kw) { }
}

public sealed partial class UshortType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"ushort", Priority = 1)] Token kw) { }
}

public sealed partial class UintType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"uint", Priority = 1)] Token kw) { }
}

public sealed partial class UlongType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"ulong", Priority = 1)] Token kw) { }
}

public sealed partial class LongType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"long", Priority = 1)] Token kw) { }
}

public sealed partial class DecimalType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"decimal", Priority = 1)] Token kw) { }
}

public sealed partial class ObjectType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"object", Priority = 1)] Token kw) { }
}

public sealed partial class VoidType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"void", Priority = 1)] Token kw) { }
}

public sealed partial class VarType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"var", Priority = 1)] Token kw) { }
}

public sealed partial class DynamicType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"dynamic", Priority = 1)] Token kw) { }
}

public sealed partial class NintType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"nint", Priority = 1)] Token kw) { }
}

public sealed partial class NuintType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"nuint", Priority = 1)] Token kw) { }
}

public sealed partial class NamedType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class ArrayType : Type
{
    [Rule]
    public static void Reduce(Type element, [Pattern(@"\[")] Token lb, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class GenericType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"<")] Token lt, TypeArgumentList args, [Pattern(@">")] Token gt) { }
}

public abstract partial class TypeArgumentList : AstNode { }

public sealed partial class SingleTypeArg : TypeArgumentList
{
    [Rule]
    public static void Reduce(Type type) { }
}

public sealed partial class ConsTypeArg : TypeArgumentList
{
    [Rule]
    public static void Reduce(TypeArgumentList list, [Pattern(@",")] Token comma, Type type) { }
}

[Precedence(15)]
public sealed partial class NullableType : Type
{
    [Rule]
    public static void Reduce(Type element, [Pattern(@"\?")] Token question) { }
}

[Precedence(15)]
public sealed partial class PointerType : Type
{
    [Rule]
    public static void Reduce(Type element, [Pattern(@"\*")] Token star) { }
}

public sealed partial class FunctionPointerType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"delegate\*", Priority = 1)] Token delegatePtr, [Pattern(@"<")] Token lt, FpTypeList args, [Pattern(@">")] Token gt) { }
}

public abstract partial class FpTypeList : AstNode { }

public sealed partial class SingleFpType : FpTypeList
{
    [Rule]
    public static void Reduce(Type type) { }
}

public sealed partial class ConsFpType : FpTypeList
{
    [Rule]
    public static void Reduce(FpTypeList list, [Pattern(@",")] Token comma, Type type) { }
}

public sealed partial class TupleType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Type first, [Pattern(@",")] Token comma, TupleTypeList rest, [Pattern(@"\)")] Token rp) { }
}

public abstract partial class TupleTypeList : AstNode { }

public sealed partial class SingleTupleElement : TupleTypeList
{
    [Rule]
    public static void Reduce(Type type) { }
}

public sealed partial class ConsTupleElement : TupleTypeList
{
    [Rule]
    public static void Reduce(TupleTypeList list, [Pattern(@",")] Token comma, Type type) { }
}

[Precedence(15)]
public sealed partial class RefType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"ref", Priority = 1)] Token refKw, Type element) { }
}

[Precedence(15)]
public sealed partial class RefReadOnlyType : Type
{
    [Rule]
    public static void Reduce([Pattern(@"ref", Priority = 1)] Token refKw, [Pattern(@"readonly", Priority = 1)] Token readonlyKw, Type element) { }
}

[Precedence(15)]
public sealed partial class MultiDimensionalArrayType : Type
{
    [Rule]
    public static void Reduce(Type element, [Pattern(@"\[")] Token lb, RankCommaList commas, [Pattern(@"\]")] Token rb) { }
}

public abstract partial class RankCommaList : AstNode { }

public sealed partial class SingleRankComma : RankCommaList
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma) { }
}

public sealed partial class ConsRankComma : RankCommaList
{
    [Rule]
    public static void Reduce(RankCommaList list, [Pattern(@",")] Token comma) { }
}

public abstract partial class Expression : AstNode { }

public abstract partial class ArgumentList : AstNode { }

public sealed partial class NilArgumentList : ArgumentList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleArgument : ArgumentList
{
    [Rule]
    public static void Reduce(Expression head, ArgumentTail tail) { }
}

public abstract partial class ArgumentTail : AstNode { }

public sealed partial class NilArgumentTail : ArgumentTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsArgumentTail : ArgumentTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma, Expression head, ArgumentTail tail) { }
}

public sealed partial class IntegerLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+")] Token value) { }
}

public sealed partial class RealLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+\.[0-9]+")] Token value) { }
}

public sealed partial class StringLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"""([^""\\]|\\.)*""")] Token value) { }
}

public sealed partial class CharLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"'([^'\\]|\\.)'")] Token value) { }
}

public sealed partial class TrueLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"true", Priority = 1)] Token kw) { }
}

public sealed partial class FalseLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"false", Priority = 1)] Token kw) { }
}

public sealed partial class NullLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"null", Priority = 1)] Token kw) { }
}

public sealed partial class IdentifierExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class ThisExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"this", Priority = 1)] Token kw) { }
}

public sealed partial class ParenExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Expression inner, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed partial class MemberAccess : Expression
{
    [Rule]
    public static void Reduce(Expression target, [Pattern(@"\.")] Token dot, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

[Precedence(15)]
public sealed partial class Invocation : Expression
{
    [Rule]
    public static void Reduce(Expression target, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed partial class PostIncrement : Expression
{
    [Rule]
    public static void Reduce(Expression operand, [Pattern(@"\+\+")] Token op) { }
}

[Precedence(15)]
public sealed partial class PostDecrement : Expression
{
    [Rule]
    public static void Reduce(Expression operand, [Pattern(@"--")] Token op) { }
}

public abstract partial class TupleElementList : AstNode { }

public sealed partial class SingleTupleElementList : TupleElementList
{
    [Rule]
    public static void Reduce(Expression head, TupleElementTail tail) { }
}

public abstract partial class TupleElementTail : AstNode { }

public sealed partial class NilTupleElementTail : TupleElementTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsTupleElementTail : TupleElementTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token sep, Expression head, TupleElementTail tail) { }
}

public abstract partial class InitializerList : AstNode { }

public sealed partial class NilInitializerList : InitializerList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleInitializerList : InitializerList
{
    [Rule]
    public static void Reduce(Expression head, InitializerTail tail) { }
}

public abstract partial class InitializerTail : AstNode { }

public sealed partial class NilInitializerTail : InitializerTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsInitializerTail : InitializerTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token sep, Expression head, InitializerTail tail) { }
}

public abstract partial class CollectionElementList : AstNode { }

public sealed partial class NilCollectionElementList : CollectionElementList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleCollectionElementList : CollectionElementList
{
    [Rule]
    public static void Reduce(Expression head, CollectionElementTail tail) { }
}

public abstract partial class CollectionElementTail : AstNode { }

public sealed partial class NilCollectionElementTail : CollectionElementTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsCollectionElementTail : CollectionElementTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token sep, Expression head, CollectionElementTail tail) { }
}

public abstract partial class LambdaParameterList : AstNode { }

public sealed partial class NilLambdaParameterList : LambdaParameterList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleLambdaParameterList : LambdaParameterList
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, LambdaParameterTail tail) { }
}

public abstract partial class LambdaParameterTail : AstNode { }

public sealed partial class NilLambdaParameterTail : LambdaParameterTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsLambdaParameterTail : LambdaParameterTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token sep, [Pattern(@"[A-Za-z_]\w*")] Token name, LambdaParameterTail tail) { }
}

public abstract partial class SwitchExprArmList : AstNode { }

public sealed partial class NilSwitchExprArmList : SwitchExprArmList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleSwitchExprArmList : SwitchExprArmList
{
    [Rule]
    public static void Reduce(SwitchExprArm arm) { }
}

public sealed partial class ConsSwitchExprArmList : SwitchExprArmList
{
    [Rule]
    public static void Reduce(SwitchExprArm head, [Pattern(@",")] Token sep, SwitchExprArmList rest) { }
}

public abstract partial class SwitchExprArm : AstNode { }

public sealed partial class PatternArm : SwitchExprArm
{
    [Rule]
    public static void Reduce(Pattern pattern, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public sealed partial class DiscardArm : SwitchExprArm
{
    [Rule]
    public static void Reduce([Pattern(@"_")] Token discard, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public abstract partial class QueryClauseList : AstNode { }

public sealed partial class SingleQueryClause : QueryClauseList
{
    [Rule]
    public static void Reduce(QueryClause head) { }
}

public sealed partial class ConsQueryClauseList : QueryClauseList
{
    [Rule]
    public static void Reduce(QueryClause head, QueryClauseList rest) { }
}

public abstract partial class QueryClause : AstNode { }

[Precedence(1)]
public sealed partial class FromClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"from", Priority = 1)] Token kwFrom, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token kwIn, Expression source) { }
}

[Precedence(1)]
public sealed partial class SelectClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"select", Priority = 1)] Token kwSelect, Expression selector) { }
}

[Precedence(1)]
public sealed partial class WhereClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"where", Priority = 1)] Token kwWhere, Expression condition) { }
}

[Precedence(1)]
public sealed partial class OrderByClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"orderby", Priority = 1)] Token kwOrderBy, Expression key) { }
}

[Precedence(1)]
public sealed partial class GroupClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"group", Priority = 1)] Token kwGroup, Expression element, [Pattern(@"by", Priority = 1)] Token kwBy, Expression key) { }
}

[Precedence(1)]
public sealed partial class LetClause : QueryClause
{
    [Rule]
    public static void Reduce([Pattern(@"let", Priority = 1)] Token kwLet, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public sealed partial class BaseExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"base", Priority = 1)] Token kw) { }
}

public sealed partial class HexLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"0[xX][0-9a-fA-F_]+")] Token value) { }
}

public sealed partial class BinaryLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"0[bB][01_]+")] Token value) { }
}

public sealed partial class VerbatimStringLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"@""(""""|[^""])*""")] Token value) { }
}

public sealed partial class InterpolatedStringLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\$\$(""""|[^""])*""")] Token value) { }
}

public sealed partial class RawStringLiteral : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\""""[\s\S]*?\""""")] Token value) { }
}

public sealed partial class NameofExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"nameof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, QualifiedName name, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class TypeofExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"typeof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class SizeofExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"sizeof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class StackallocExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"stackalloc", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb) { }
}

public sealed partial class TupleExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Expression first, [Pattern(@",")] Token sep, TupleElementList rest, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class CollectionExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\[")] Token lb, CollectionElementList elements, [Pattern(@"\]")] Token rb) { }
}

[Precedence(14)]
public sealed partial class IndexExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\^")] Token hat, Expression expr) { }
}

[Precedence(15)]
public sealed partial class ElementAccess : Expression
{
    [Rule]
    public static void Reduce(Expression target, [Pattern(@"\[")] Token lb, ArgumentList args, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class NullConditionalMember : Expression
{
    [Rule]
    public static void Reduce(Expression target, [Pattern(@"\?\.")] Token op, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

[Precedence(15)]
public sealed partial class NullConditionalIndex : Expression
{
    [Rule]
    public static void Reduce(Expression target, [Pattern(@"\?\[")] Token op, ArgumentList args, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class RangeExpr : Expression
{
    [Rule]
    public static void Reduce(Expression from, [Pattern(@"\.\.")] Token op, Expression to) { }
}

[Precedence(14)]
public sealed partial class PreIncrementExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\+\+")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed partial class PreDecrementExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"--")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed partial class IndirectionExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\*")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed partial class AddressOfExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"&")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed partial class CastExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp, Expression expr) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class AssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class AddAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\+=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class SubAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"-=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class MulAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\*=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class DivAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"/=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class ModAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"%=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class AndAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"&=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class OrAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\|=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class XorAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\^=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class LeftShiftAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"<<=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class RightShiftAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@">>=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class CoalesceAssignExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\?\?=")] Token op, Expression right) { }
}

[Precedence(2, IsRightAssociative = true)]
public sealed partial class ConditionalExpr : Expression
{
    [Rule]
    public static void Reduce(Expression cond, [Pattern(@"\?")] Token question, Expression then, [Pattern(@":")] Token colon, Expression elseBranch) { }
}

[Precedence(3)]
public sealed partial class CoalesceExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\?\?")] Token op, Expression right) { }
}

[Precedence(4)]
public sealed partial class OrExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\|\|")] Token op, Expression right) { }
}

[Precedence(5)]
public sealed partial class AndExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"&&")] Token op, Expression right) { }
}

[Precedence(6)]
public sealed partial class BitOrExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\|")] Token op, Expression right) { }
}

[Precedence(7)]
public sealed partial class BitXorExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\^")] Token op, Expression right) { }
}

[Precedence(8)]
public sealed partial class BitAndExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"&")] Token op, Expression right) { }
}

[Precedence(9)]
public sealed partial class EqualExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"==")] Token op, Expression right) { }
}

[Precedence(9)]
public sealed partial class NotEqualExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"!=")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed partial class LessExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"<")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed partial class GreaterExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@">")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed partial class LessEqualExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"<=")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed partial class GreaterEqualExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@">=")] Token op, Expression right) { }
}

[Precedence(11)]
public sealed partial class LeftShiftExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"<<")] Token op, Expression right) { }
}

[Precedence(11)]
public sealed partial class RightShiftExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@">>")] Token op, Expression right) { }
}

[Precedence(12)]
public sealed partial class AddExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\+")] Token op, Expression right) { }
}

[Precedence(12)]
public sealed partial class SubExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"-")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed partial class MulExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"\*")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed partial class DivExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"/")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed partial class ModExpr : Expression
{
    [Rule]
    public static void Reduce(Expression left, [Pattern(@"%")] Token op, Expression right) { }
}

[Precedence(14)]
public sealed partial class AwaitExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"await", Priority = 1)] Token kw, Expression expr) { }
}

[Precedence(10)]
public sealed partial class IsPatternExpr : Expression
{
    [Rule]
    public static void Reduce(Expression expr, [Pattern(@"is", Priority = 1)] Token kw, Pattern pattern) { }
}

[Precedence(10)]
public sealed partial class AsExpr : Expression
{
    [Rule]
    public static void Reduce(Expression expr, [Pattern(@"as", Priority = 1)] Token kw, Type type) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class SimpleLambdaExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token param, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public sealed partial class AnonymousMethodExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"delegate", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class AnonymousMethodParamsExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"delegate", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, LambdaParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class ObjectCreationExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class ObjectCreationInitExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class ObjectCreationEmptyInitExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class ArrayCreationExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb) { }
}

public sealed partial class ArrayCreationInitExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lb2, InitializerList initializers, [Pattern(@"\}")] Token rb2) { }
}

public sealed partial class ImplicitArrayCreationExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\[")] Token lb, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lb2, InitializerList initializers, [Pattern(@"\}")] Token rb2) { }
}

public sealed partial class TargetTypedNewExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class TargetTypedNewInitExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed partial class WithExpr : Expression
{
    [Rule]
    public static void Reduce(Expression expr, [Pattern(@"with", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed partial class SwitchExpr : Expression
{
    [Rule]
    public static void Reduce(Expression governor, [Pattern(@"switch", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, SwitchExprArmList arms, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class QueryExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"from", Priority = 1)] Token kwFrom, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token kwIn, Expression source, QueryClauseList clauses) { }
}

[Precedence(1)]
public sealed partial class ThrowExpr : Expression
{
    [Rule]
    public static void Reduce([Pattern(@"throw", Priority = 1)] Token kw, Expression expr) { }
}

public abstract partial class Pattern : AstNode { }

public sealed partial class NullConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"null", Priority = 1)] Token kw) { }
}

public sealed partial class TrueConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"true", Priority = 1)] Token kw) { }
}

public sealed partial class FalseConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"false", Priority = 1)] Token kw) { }
}

public sealed partial class IntConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+[dDfFlLmMuU]*")] Token value) { }
}

public sealed partial class RealConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]*")] Token value) { }
}

public sealed partial class HexConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"0[xX][0-9a-fA-F_]+")] Token value) { }
}

public sealed partial class BinaryConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"0[bB][01_]+")] Token value) { }
}

public sealed partial class CharConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"'([^'\\]|\\.)'")] Token value) { }
}

public sealed partial class StringConstantPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"""([^""\\]|\\.)*""")] Token value) { }
}

public sealed partial class TypePattern : Pattern
{
    [Rule]
    public static void Reduce(Type type) { }
}

public sealed partial class DeclarationPattern : Pattern
{
    [Rule]
    public static void Reduce(Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class VarPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class DiscardPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"_", Priority = 1)] Token underscore) { }
}

[Precedence(15)]
public sealed partial class ParenPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Pattern inner, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed partial class ListPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"\[")] Token lb, ListPatternElemList elements, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class SlicePattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"\[")] Token lb, [Pattern(@"\.\.")] Token slice, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class PropertyPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"\{")] Token lb, PropPatternList properties, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed partial class PositionalPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Pattern first, [Pattern(@",")] Token comma, PositionalRestList rest, [Pattern(@"\)")] Token rp) { }
}

[Precedence(14)]
public sealed partial class LessThanPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"<")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed partial class GreaterThanPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@">")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed partial class LessThanOrEqualPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"<=")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed partial class GreaterThanOrEqualPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@">=")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed partial class NotPattern : Pattern
{
    [Rule]
    public static void Reduce([Pattern(@"not", Priority = 1)] Token notKw, Pattern operand) { }
}

[Precedence(8)]
public sealed partial class AndPattern : Pattern
{
    [Rule]
    public static void Reduce(Pattern left, [Pattern(@"and", Priority = 1)] Token andKw, Pattern right) { }
}

[Precedence(6)]
public sealed partial class OrPattern : Pattern
{
    [Rule]
    public static void Reduce(Pattern left, [Pattern(@"or", Priority = 1)] Token orKw, Pattern right) { }
}

public abstract partial class ListPatternElemList : AstNode { }

public sealed partial class NilListPatternElem : ListPatternElemList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleListPatternElem : ListPatternElemList
{
    [Rule]
    public static void Reduce(Pattern head, ListPatternElemTail tail) { }
}

public abstract partial class ListPatternElemTail : AstNode { }

public sealed partial class NilListPatternElemTail : ListPatternElemTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsListPatternElemTail : ListPatternElemTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma, Pattern head, ListPatternElemTail tail) { }
}

public abstract partial class PositionalRestList : AstNode { }

public sealed partial class SinglePositionalRest : PositionalRestList
{
    [Rule]
    public static void Reduce(Pattern head, PositionalRestTail tail) { }
}

public abstract partial class PositionalRestTail : AstNode { }

public sealed partial class NilPositionalRestTail : PositionalRestTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsPositionalRestTail : PositionalRestTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma, Pattern head, PositionalRestTail tail) { }
}

public abstract partial class PropPatternList : AstNode { }

public sealed partial class NilPropPatternList : PropPatternList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SinglePropPattern : PropPatternList
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Pattern value) { }
}

public sealed partial class ConsPropPattern : PropPatternList
{
    [Rule]
    public static void Reduce(PropPatternList list, [Pattern(@",")] Token comma, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Pattern value) { }
}

public abstract partial class Statement : AstNode { }

public sealed partial class EmptyStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@";")] Token semi) { }
}

public sealed partial class ExpressionStatement : Statement
{
    [Rule]
    public static void Reduce(Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class VarDeclaration : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed partial class LocalConstantDeclaration : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"const", Priority = 1)] Token constKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed partial class IfStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"if", Priority = 1)] Token ifKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement then) { }
}

public sealed partial class IfElseStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"if", Priority = 1)] Token ifKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement then, [Pattern(@"else", Priority = 1)] Token elseKw, Statement elseBranch) { }
}

public sealed partial class WhileStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"while", Priority = 1)] Token whileKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ReturnStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"return", Priority = 1)] Token returnKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class ReturnExprStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"return", Priority = 1)] Token returnKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class BreakStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"break", Priority = 1)] Token breakKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class ContinueStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"continue", Priority = 1)] Token continueKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class BlockStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class BlockStatementWithBody : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"\{")] Token lb, StatementList body, [Pattern(@"\}")] Token rb) { }
}

public abstract partial class StatementList : AstNode { }

public sealed partial class SingleStatement : StatementList
{
    [Rule]
    public static void Reduce(Statement head) { }
}

public sealed partial class ConsStatement : StatementList
{
    [Rule]
    public static void Reduce(Statement head, StatementList rest) { }
}

public abstract partial class SwitchSectionStatementList : AstNode { }

public sealed partial class SingleSwitchSectionStatement : SwitchSectionStatementList
{
    [Rule]
    public static void Reduce(Statement head) { }
}

public sealed partial class ConsSwitchSectionStatement : SwitchSectionStatementList
{
    [Rule]
    public static void Reduce(Statement head, SwitchSectionStatementList rest) { }
}

public abstract partial class ForInit : AstNode { }

public sealed partial class NilForInit : ForInit
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ForInitVar : ForInit
{
    [Rule]
    public static void Reduce([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init) { }
}

public sealed partial class ForInitExprList : ForInit
{
    [Rule]
    public static void Reduce(Expression head, ForInitExprTail tail) { }
}

public abstract partial class ForInitExprTail : AstNode { }

public sealed partial class NilForInitExprTail : ForInitExprTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsForInitExprTail : ForInitExprTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma, Expression head, ForInitExprTail tail) { }
}

public abstract partial class ForUpdate : AstNode { }

public sealed partial class NilForUpdate : ForUpdate
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ForUpdateExprList : ForUpdate
{
    [Rule]
    public static void Reduce(Expression head, ForUpdateExprTail tail) { }
}

public abstract partial class ForUpdateExprTail : AstNode { }

public sealed partial class NilForUpdateExprTail : ForUpdateExprTail
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsForUpdateExprTail : ForUpdateExprTail
{
    [Rule]
    public static void Reduce([Pattern(@",")] Token comma, Expression head, ForUpdateExprTail tail) { }
}

public abstract partial class ForCondition : AstNode { }

public sealed partial class NilForCondition : ForCondition
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ForConditionExpr : ForCondition
{
    [Rule]
    public static void Reduce(Expression cond) { }
}

public sealed partial class ForStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"for", Priority = 1)] Token forKw, [Pattern(@"\(")] Token lp, ForInit init, [Pattern(@";")] Token semi1, ForCondition cond, [Pattern(@";")] Token semi2, ForUpdate update, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ForEachStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"foreach", Priority = 1)] Token foreachKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token inKw, Expression collection, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ForEachVarStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"foreach", Priority = 1)] Token foreachKw, [Pattern(@"\(")] Token lp, [Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token inKw, Expression collection, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class DoStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"do", Priority = 1)] Token doKw, Statement body, [Pattern(@"while", Priority = 1)] Token whileKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, [Pattern(@";")] Token semi) { }
}

public abstract partial class CaseLabel : AstNode { }

public sealed partial class CaseExprLabel : CaseLabel
{
    [Rule]
    public static void Reduce([Pattern(@"case", Priority = 1)] Token caseKw, Expression value, [Pattern(@":")] Token colon) { }
}

public sealed partial class DefaultLabel : CaseLabel
{
    [Rule]
    public static void Reduce([Pattern(@"default", Priority = 1)] Token defaultKw, [Pattern(@":")] Token colon) { }
}

public abstract partial class CaseLabelList : AstNode { }

public sealed partial class SingleCaseLabel : CaseLabelList
{
    [Rule]
    public static void Reduce(CaseLabel head) { }
}

public sealed partial class ConsCaseLabel : CaseLabelList
{
    [Rule]
    public static void Reduce(CaseLabelList list, CaseLabel label) { }
}

public abstract partial class SwitchSection : AstNode { }

public sealed partial class LabeledSwitchSection : SwitchSection
{
    [Rule]
    public static void Reduce(CaseLabelList labels, SwitchSectionStatementList body) { }
}

public abstract partial class SwitchSectionList : AstNode { }

public sealed partial class NilSwitchSection : SwitchSectionList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsSwitchSection : SwitchSectionList
{
    [Rule]
    public static void Reduce(SwitchSection head, SwitchSectionList rest) { }
}

public sealed partial class SwitchStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"switch", Priority = 1)] Token switchKw, [Pattern(@"\(")] Token lp, Expression expr, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, SwitchSectionList sections, [Pattern(@"\}")] Token rb) { }
}

public abstract partial class CatchClause : AstNode { }

public sealed partial class CatchTypeClause : CatchClause
{
    [Rule]
    public static void Reduce([Pattern(@"catch", Priority = 1)] Token catchKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class CatchTypeOnlyClause : CatchClause
{
    [Rule]
    public static void Reduce([Pattern(@"catch", Priority = 1)] Token catchKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class CatchGeneralClause : CatchClause
{
    [Rule]
    public static void Reduce([Pattern(@"catch", Priority = 1)] Token catchKw, Statement body) { }
}

public abstract partial class CatchClauseList : AstNode { }

public sealed partial class NilCatchClause : CatchClauseList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsCatchClause : CatchClauseList
{
    [Rule]
    public static void Reduce(CatchClause head, CatchClauseList rest) { }
}

public abstract partial class FinallyClause : AstNode { }

public sealed partial class NilFinallyClause : FinallyClause
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class PresentFinallyClause : FinallyClause
{
    [Rule]
    public static void Reduce([Pattern(@"finally", Priority = 1)] Token finallyKw, Statement body) { }
}

public sealed partial class TryStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"try", Priority = 1)] Token tryKw, Statement body, CatchClauseList catchClauses, FinallyClause finallyClause) { }
}

public sealed partial class LockStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"lock", Priority = 1)] Token lockKw, [Pattern(@"\(")] Token lp, Expression expr, [Pattern(@"\)")] Token rp, Statement body) { }
}

public abstract partial class UsingResource : AstNode { }

public sealed partial class UsingExprResource : UsingResource
{
    [Rule]
    public static void Reduce(Expression expr) { }
}

public sealed partial class UsingVarResource : UsingResource
{
    [Rule]
    public static void Reduce([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init) { }
}

public sealed partial class UsingStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"using", Priority = 1)] Token usingKw, [Pattern(@"\(")] Token lp, UsingResource resource, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class FixedStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"fixed", Priority = 1)] Token fixedKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\*")] Token star, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class CheckedStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"checked", Priority = 1)] Token checkedKw, Statement body) { }
}

public sealed partial class UncheckedStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"unchecked", Priority = 1)] Token uncheckedKw, Statement body) { }
}

public sealed partial class UnsafeStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"unsafe", Priority = 1)] Token unsafeKw, Statement body) { }
}

public sealed partial class YieldReturnStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"yield", Priority = 1)] Token yieldKw, [Pattern(@"return", Priority = 1)] Token returnKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class YieldBreakStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"yield", Priority = 1)] Token yieldKw, [Pattern(@"break", Priority = 1)] Token breakKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class GotoStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed partial class GotoCaseStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"case", Priority = 1)] Token caseKw, Expression value, [Pattern(@";")] Token semi) { }
}

public sealed partial class GotoDefaultStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"default", Priority = 1)] Token defaultKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class LabeledStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Statement body) { }
}

public sealed partial class ThrowStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"throw", Priority = 1)] Token throwKw, [Pattern(@";")] Token semi) { }
}

public sealed partial class ThrowExprStatement : Statement
{
    [Rule]
    public static void Reduce([Pattern(@"throw", Priority = 1)] Token throwKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public abstract partial class QualifiedName : AstNode { }

public sealed partial class SimpleQualifiedName : QualifiedName
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class QualifiedQualifiedName : QualifiedName
{
    [Rule]
    public static void Reduce(QualifiedName left, [Pattern(@"\.")] Token dot, [Pattern(@"[A-Za-z_]\w*")] Token right) { }
}

public abstract partial class ModifierList : AstNode { }

public sealed partial class NilModifierList : ModifierList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsModifier : ModifierList
{
    [Rule]
    public static void Reduce([Pattern(@"(public|private|protected|internal|static|readonly|abstract|sealed|const|async|virtual|override|extern|partial|unsafe|volatile)", Priority = 1)] Token modifier, ModifierList rest) { }
}

public abstract partial class Declaration : AstNode { }

public sealed partial class UsingDirective : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"using", Priority = 1)] Token usingKw, QualifiedName ns, [Pattern(@";")] Token semi) { }
}

public sealed partial class NamespaceDeclaration : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"namespace", Priority = 1)] Token namespaceKw, QualifiedName name, [Pattern(@"\{")] Token lb, NamespaceBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class ClassDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"class", Priority = 1)] Token classKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public abstract partial class NamespaceBody : AstNode { }

public sealed partial class NilNamespaceBody : NamespaceBody
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsNamespaceMember : NamespaceBody
{
    [Rule]
    public static void Reduce(Declaration head, NamespaceBody rest) { }
}

public abstract partial class TypeParameter : AstNode { }

public sealed partial class PlainTypeParameter : TypeParameter
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public abstract partial class TypeParameterList : AstNode { }

public sealed partial class SingleTypeParameter : TypeParameterList
{
    [Rule]
    public static void Reduce([Pattern(@"<")] Token lt, TypeParameter head) { }
}

public sealed partial class ConsTypeParameter : TypeParameterList
{
    [Rule]
    public static void Reduce(TypeParameterList list, [Pattern(@",")] Token comma, TypeParameter next) { }
}

public abstract partial class OptionalTypeParameterList : AstNode { }

public sealed partial class AbsentTypeParameterList : OptionalTypeParameterList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class PresentTypeParameterList : OptionalTypeParameterList
{
    [Rule]
    public static void Reduce(TypeParameterList list, [Pattern(@">")] Token gt) { }
}

public abstract partial class BaseList : AstNode { }

public sealed partial class NilBaseList : BaseList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleBaseType : BaseList
{
    [Rule]
    public static void Reduce([Pattern(@":")] Token colon, Type head) { }
}

public sealed partial class ConsBaseType : BaseList
{
    [Rule]
    public static void Reduce(BaseList list, [Pattern(@",")] Token comma, Type next) { }
}

public abstract partial class TypeParameterConstraint : AstNode { }

public sealed partial class ClassTypeConstraint : TypeParameterConstraint
{
    [Rule]
    public static void Reduce([Pattern(@"class", Priority = 1)] Token kw) { }
}

public sealed partial class StructTypeConstraint : TypeParameterConstraint
{
    [Rule]
    public static void Reduce([Pattern(@"struct", Priority = 1)] Token kw) { }
}

public sealed partial class TypeConstraint : TypeParameterConstraint
{
    [Rule]
    public static void Reduce(Type type) { }
}

public abstract partial class TypeParameterConstraintList : AstNode { }

public sealed partial class SingleTypeParameterConstraint : TypeParameterConstraintList
{
    [Rule]
    public static void Reduce(TypeParameterConstraint head) { }
}

public sealed partial class ConsTypeParameterConstraint : TypeParameterConstraintList
{
    [Rule]
    public static void Reduce(TypeParameterConstraintList list, [Pattern(@",")] Token comma, TypeParameterConstraint next) { }
}

public abstract partial class TypeParameterConstraintClauseList : AstNode { }

public sealed partial class NilTypeParameterConstraintClause : TypeParameterConstraintClauseList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsTypeParameterConstraintClause : TypeParameterConstraintClauseList
{
    [Rule]
    public static void Reduce([Pattern(@"where", Priority = 1)] Token whereKw, [Pattern(@"[A-Za-z_]\w*")] Token param, [Pattern(@":")] Token colon, TypeParameterConstraintList constraints, TypeParameterConstraintClauseList rest) { }
}

public sealed partial class StructDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"struct", Priority = 1)] Token structKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class InterfaceDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"interface", Priority = 1)] Token interfaceKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class EnumDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"enum", Priority = 1)] Token enumKw, [Pattern(@"[A-Za-z_]\w*")] Token name, BaseList bases, [Pattern(@"\{")] Token lb, EnumMemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class DelegateDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"delegate", Priority = 1)] Token delegateKw, Type returnType, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@";")] Token semi) { }
}

public sealed partial class RecordDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"record", Priority = 1)] Token recordKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, BaseList bases, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class RecordStructDeclaration : Declaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"record", Priority = 1)] Token recordKw, [Pattern(@"struct", Priority = 1)] Token structKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class FileScopedNamespaceDeclaration : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"namespace", Priority = 1)] Token namespaceKw, QualifiedName name, [Pattern(@";")] Token semi) { }
}

public sealed partial class GlobalUsingDirective : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"global", Priority = 1)] Token globalKw, [Pattern(@"using", Priority = 1)] Token usingKw, QualifiedName ns, [Pattern(@";")] Token semi) { }
}

public sealed partial class GlobalUsingAliasDirective : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"global", Priority = 1)] Token globalKw, [Pattern(@"using", Priority = 1)] Token usingKw, [Pattern(@"[A-Za-z_]\w*")] Token alias, [Pattern(@"=")] Token eq, Type target, [Pattern(@";")] Token semi) { }
}

public sealed partial class ExternAliasDirective : Declaration
{
    [Rule]
    public static void Reduce([Pattern(@"extern", Priority = 1)] Token externKw, [Pattern(@"alias", Priority = 1)] Token aliasKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public abstract partial class EnumMemberBody : AstNode { }

public sealed partial class NilEnumMember : EnumMemberBody
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleEnumMember : EnumMemberBody
{
    [Rule]
    public static void Reduce(EnumMember head) { }
}

public sealed partial class ConsEnumMember : EnumMemberBody
{
    [Rule]
    public static void Reduce(EnumMember head, [Pattern(@",")] Token comma, EnumMemberBody rest) { }
}

public abstract partial class EnumMember : AstNode { }

public sealed partial class EnumMemberDecl : EnumMember
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class EnumMemberInitDecl : EnumMember
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public abstract partial class ParameterList : AstNode { }

public sealed partial class NilParameterList : ParameterList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class SingleParameter : ParameterList
{
    [Rule]
    public static void Reduce(Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class ConsParameter : ParameterList
{
    [Rule]
    public static void Reduce(ParameterList list, [Pattern(@",")] Token comma, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public abstract partial class AccessorList : AstNode { }

public sealed partial class NilAccessorList : AccessorList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsAccessor : AccessorList
{
    [Rule]
    public static void Reduce(Accessor head, AccessorList rest) { }
}

public abstract partial class Accessor : AstNode { }

public sealed partial class GetAccessor : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"get", Priority = 1)] Token kw, Statement body) { }
}

public sealed partial class GetAccessorExprBody : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"get", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class SetAccessor : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"set", Priority = 1)] Token kw, Statement body) { }
}

public sealed partial class SetAccessorExprBody : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"set", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class InitAccessor : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"init", Priority = 1)] Token kw, Statement body) { }
}

public sealed partial class InitAccessorExprBody : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"init", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class AddAccessor : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"add", Priority = 1)] Token kw, Statement body) { }
}

public sealed partial class AddAccessorExprBody : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"add", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class RemoveAccessor : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"remove", Priority = 1)] Token kw, Statement body) { }
}

public sealed partial class RemoveAccessorExprBody : Accessor
{
    [Rule]
    public static void Reduce([Pattern(@"remove", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public abstract partial class MemberDeclaration : AstNode { }

public sealed partial class FieldDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed partial class MethodDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, Type returnType, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class PropertyDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\{")] Token lb, AccessorList accessors, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class IndexerDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, Type type, [Pattern(@"this", Priority = 1)] Token thisKw, [Pattern(@"\[")] Token lb, ParameterList parameters, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lbrace, AccessorList accessors, [Pattern(@"\}")] Token rbrace) { }
}

public sealed partial class EventDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\{")] Token lb, AccessorList accessors, [Pattern(@"\}")] Token rb) { }
}

public sealed partial class EventFieldDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed partial class EventFieldWithInitDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed partial class ImplicitOperatorDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"implicit", Priority = 1)] Token implicitKw, [Pattern(@"operator", Priority = 1)] Token operatorKw, Type targetType, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ExplicitOperatorDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"explicit", Priority = 1)] Token explicitKw, [Pattern(@"operator", Priority = 1)] Token operatorKw, Type targetType, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ConstructorDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class ConstructorWithInitializerDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@":")] Token colon, [Pattern(@"base", Priority = 1)] Token baseKw, [Pattern(@"\(")] Token initLp, ArgumentList args, [Pattern(@"\)")] Token initRp, Statement body) { }
}

public sealed partial class StaticConstructorDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed partial class FinalizerDeclaration : MemberDeclaration
{
    [Rule]
    public static void Reduce([Pattern(@"~")] Token tilde, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, [Pattern(@"\)")] Token rp, Statement body) { }
}

public abstract partial class MemberBody : AstNode { }

public sealed partial class NilMemberBody : MemberBody
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsMemberDecl : MemberBody
{
    [Rule]
    public static void Reduce(MemberDeclaration head, MemberBody rest) { }
}

public abstract partial class AttributeSectionList : AstNode { }

public sealed partial class NilAttributeSection : AttributeSectionList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsAttributeSection : AttributeSectionList
{
    [Rule]
    public static void Reduce(AttributeSection head, AttributeSectionList rest) { }
}

public abstract partial class AttributeSection : AstNode { }

public sealed partial class AttributeSectionNoTarget : AttributeSection
{
    [Rule]
    public static void Reduce([Pattern(@"\[")] Token lb, AttributeList attributes, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed partial class AttributeSectionWithTarget : AttributeSection
{
    [Rule]
    public static void Reduce([Pattern(@"\[")] Token lb, [Pattern(@"[A-Za-z_]\w*")] Token target, [Pattern(@":")] Token colon, AttributeList attributes, [Pattern(@"\]")] Token rb) { }
}

public abstract partial class AttributeList : AstNode { }

public sealed partial class SingleAttribute : AttributeList
{
    [Rule]
    public static void Reduce(Attribute head) { }
}

public sealed partial class ConsAttribute : AttributeList
{
    [Rule]
    public static void Reduce(AttributeList list, [Pattern(@",")] Token comma, Attribute head) { }
}

public abstract partial class Attribute : AstNode { }

public sealed partial class AttributeDecl : Attribute
{
    [Rule]
    public static void Reduce(QualifiedName name) { }
}

public sealed partial class AttributeDeclWithArgs : Attribute
{
    [Rule]
    public static void Reduce(QualifiedName name, [Pattern(@"\(")] Token lp, AttributeArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public abstract partial class AttributeArgumentList : AstNode { }

public sealed partial class NilAttributeArgument : AttributeArgumentList
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsAttributeArgument : AttributeArgumentList
{
    [Rule]
    public static void Reduce(AttributeArgumentList list, [Pattern(@",")] Token comma, AttributeArg arg) { }
}

public sealed partial class SingleAttributeArgument : AttributeArgumentList
{
    [Rule]
    public static void Reduce(AttributeArg arg) { }
}

public abstract partial class AttributeArg : AstNode { }

public sealed partial class PositionalAttributeArg : AttributeArg
{
    [Rule]
    public static void Reduce(Expression value) { }
}

[Precedence(15)]
public sealed partial class NamedAttributeArg : AttributeArg
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public abstract partial class PPDirective : AstNode { }

public abstract partial class PPExpr : AstNode { }

public sealed partial class PPSymbolExpr : PPExpr
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

[Precedence(14)]
public sealed partial class PPNotExpr : PPExpr
{
    [Rule]
    public static void Reduce([Pattern(@"!")] Token bang, PPExpr operand) { }
}

[Precedence(9)]
public sealed partial class PPEqExpr : PPExpr
{
    [Rule]
    public static void Reduce(PPExpr left, [Pattern(@"==")] Token op, PPExpr right) { }
}

[Precedence(9)]
public sealed partial class PPNeExpr : PPExpr
{
    [Rule]
    public static void Reduce(PPExpr left, [Pattern(@"!=")] Token op, PPExpr right) { }
}

[Precedence(5)]
public sealed partial class PPAndExpr : PPExpr
{
    [Rule]
    public static void Reduce(PPExpr left, [Pattern(@"&&")] Token op, PPExpr right) { }
}

[Precedence(4)]
public sealed partial class PPOrExpr : PPExpr
{
    [Rule]
    public static void Reduce(PPExpr left, [Pattern(@"\|\|")] Token op, PPExpr right) { }
}

public sealed partial class PPParenExpr : PPExpr
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, PPExpr inner, [Pattern(@"\)")] Token rp) { }
}

public sealed partial class PPDefine : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"define", Priority = 1)] Token kwDefine, [Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

public sealed partial class PPUndef : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"undef", Priority = 1)] Token kwUndef, [Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

public sealed partial class PPIf : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"if", Priority = 1)] Token kwIf, PPExpr condition) { }
}

public sealed partial class PPElif : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"elif", Priority = 1)] Token kwElif, PPExpr condition) { }
}

public sealed partial class PPElse : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"else", Priority = 1)] Token kwElse) { }
}

public sealed partial class PPEndIf : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"endif", Priority = 1)] Token kwEndif) { }
}

public sealed partial class PPRegion : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"region", Priority = 1)] Token kwRegion, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPEndRegion : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"endregion", Priority = 1)] Token kwEndregion, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPPragmaWarning : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"pragma", Priority = 1)] Token kwPragma, [Pattern(@"warning", Priority = 1)] Token kwWarning, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPPragmaChecksum : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"pragma", Priority = 1)] Token kwPragma, [Pattern(@"checksum", Priority = 1)] Token kwChecksum, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPLine : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"line", Priority = 1)] Token kwLine, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPNullableEnable : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"enable", Priority = 1)] Token kwEnable) { }
}

public sealed partial class PPNullableDisable : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"disable", Priority = 1)] Token kwDisable) { }
}

public sealed partial class PPNullableWarnings : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"warnings", Priority = 1)] Token kwWarnings) { }
}

public sealed partial class PPNullableAnnotations : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"annotations", Priority = 1)] Token kwAnnotations) { }
}

public sealed partial class PPError : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"error", Priority = 1)] Token kwError, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class PPWarning : PPDirective
{
    [Rule]
    public static void Reduce([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"warning", Priority = 1)] Token kwWarning2, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed partial class ConsPP : CSharpCompilationUnit
{
    [Rule]
    public static void Reduce(PPDirective directive, CSharpCompilationUnit rest) { }
}

public sealed partial class NilCompilationUnit : CSharpCompilationUnit
{
    [Rule]
    public static void Reduce() { }
}

public sealed partial class ConsDeclaration : CSharpCompilationUnit
{
    [Rule]
    public static void Reduce(Declaration head, CSharpCompilationUnit rest) { }
}

