// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace CSharpParser;

[Grammar]
[Skip(@"(\s|//[^\n]*)+")]
public abstract class CSharpCompilationUnit : AstNode { }

public abstract class Type : AstNode { }

public sealed class IntType : Type
{
    public IntType([Pattern(@"int", Priority = 1)] Token kw) { }
}

public sealed class StringType : Type
{
    public StringType([Pattern(@"string", Priority = 1)] Token kw) { }
}

public sealed class BoolType : Type
{
    public BoolType([Pattern(@"bool", Priority = 1)] Token kw) { }
}

public sealed class DoubleType : Type
{
    public DoubleType([Pattern(@"double", Priority = 1)] Token kw) { }
}

public sealed class FloatType : Type
{
    public FloatType([Pattern(@"float", Priority = 1)] Token kw) { }
}

public sealed class CharType : Type
{
    public CharType([Pattern(@"char", Priority = 1)] Token kw) { }
}

public sealed class ByteType : Type
{
    public ByteType([Pattern(@"byte", Priority = 1)] Token kw) { }
}

public sealed class SbyteType : Type
{
    public SbyteType([Pattern(@"sbyte", Priority = 1)] Token kw) { }
}

public sealed class ShortType : Type
{
    public ShortType([Pattern(@"short", Priority = 1)] Token kw) { }
}

public sealed class UshortType : Type
{
    public UshortType([Pattern(@"ushort", Priority = 1)] Token kw) { }
}

public sealed class UintType : Type
{
    public UintType([Pattern(@"uint", Priority = 1)] Token kw) { }
}

public sealed class UlongType : Type
{
    public UlongType([Pattern(@"ulong", Priority = 1)] Token kw) { }
}

public sealed class LongType : Type
{
    public LongType([Pattern(@"long", Priority = 1)] Token kw) { }
}

public sealed class DecimalType : Type
{
    public DecimalType([Pattern(@"decimal", Priority = 1)] Token kw) { }
}

public sealed class ObjectType : Type
{
    public ObjectType([Pattern(@"object", Priority = 1)] Token kw) { }
}

public sealed class VoidType : Type
{
    public VoidType([Pattern(@"void", Priority = 1)] Token kw) { }
}

public sealed class VarType : Type
{
    public VarType([Pattern(@"var", Priority = 1)] Token kw) { }
}

public sealed class DynamicType : Type
{
    public DynamicType([Pattern(@"dynamic", Priority = 1)] Token kw) { }
}

public sealed class NintType : Type
{
    public NintType([Pattern(@"nint", Priority = 1)] Token kw) { }
}

public sealed class NuintType : Type
{
    public NuintType([Pattern(@"nuint", Priority = 1)] Token kw) { }
}

public sealed class NamedType : Type
{
    public NamedType([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class ArrayType : Type
{
    public ArrayType(Type element, [Pattern(@"\[")] Token lb, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class GenericType : Type
{
    public GenericType([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"<")] Token lt, TypeArgumentList args, [Pattern(@">")] Token gt) { }
}

public abstract class TypeArgumentList : AstNode { }

public sealed class SingleTypeArg : TypeArgumentList
{
    public SingleTypeArg(Type type) { }
}

public sealed class ConsTypeArg : TypeArgumentList
{
    public ConsTypeArg(TypeArgumentList list, [Pattern(@",")] Token comma, Type type) { }
}

[Precedence(15)]
public sealed class NullableType : Type
{
    public NullableType(Type element, [Pattern(@"\?")] Token question) { }
}

[Precedence(15)]
public sealed class PointerType : Type
{
    public PointerType(Type element, [Pattern(@"\*")] Token star) { }
}

public sealed class FunctionPointerType : Type
{
    public FunctionPointerType([Pattern(@"delegate\*", Priority = 1)] Token delegatePtr, [Pattern(@"<")] Token lt, FpTypeList args, [Pattern(@">")] Token gt) { }
}

public abstract class FpTypeList : AstNode { }

public sealed class SingleFpType : FpTypeList
{
    public SingleFpType(Type type) { }
}

public sealed class ConsFpType : FpTypeList
{
    public ConsFpType(FpTypeList list, [Pattern(@",")] Token comma, Type type) { }
}

public sealed class TupleType : Type
{
    public TupleType([Pattern(@"\(")] Token lp, Type first, [Pattern(@",")] Token comma, TupleTypeList rest, [Pattern(@"\)")] Token rp) { }
}

public abstract class TupleTypeList : AstNode { }

public sealed class SingleTupleElement : TupleTypeList
{
    public SingleTupleElement(Type type) { }
}

public sealed class ConsTupleElement : TupleTypeList
{
    public ConsTupleElement(TupleTypeList list, [Pattern(@",")] Token comma, Type type) { }
}

[Precedence(15)]
public sealed class RefType : Type
{
    public RefType([Pattern(@"ref", Priority = 1)] Token refKw, Type element) { }
}

[Precedence(15)]
public sealed class RefReadOnlyType : Type
{
    public RefReadOnlyType([Pattern(@"ref", Priority = 1)] Token refKw, [Pattern(@"readonly", Priority = 1)] Token readonlyKw, Type element) { }
}

[Precedence(15)]
public sealed class MultiDimensionalArrayType : Type
{
    public MultiDimensionalArrayType(Type element, [Pattern(@"\[")] Token lb, RankCommaList commas, [Pattern(@"\]")] Token rb) { }
}

public abstract class RankCommaList : AstNode { }

public sealed class SingleRankComma : RankCommaList
{
    public SingleRankComma([Pattern(@",")] Token comma) { }
}

public sealed class ConsRankComma : RankCommaList
{
    public ConsRankComma(RankCommaList list, [Pattern(@",")] Token comma) { }
}

public abstract class Expression : AstNode { }

public abstract class ArgumentList : AstNode { }

public sealed class NilArgumentList : ArgumentList
{
    public NilArgumentList() { }
}

public sealed class SingleArgument : ArgumentList
{
    public SingleArgument(Expression head, ArgumentTail tail) { }
}

public abstract class ArgumentTail : AstNode { }

public sealed class NilArgumentTail : ArgumentTail
{
    public NilArgumentTail() { }
}

public sealed class ConsArgumentTail : ArgumentTail
{
    public ConsArgumentTail([Pattern(@",")] Token comma, Expression head, ArgumentTail tail) { }
}

public sealed class IntegerLiteral : Expression
{
    public IntegerLiteral([Pattern(@"[0-9]+")] Token value) { }
}

public sealed class RealLiteral : Expression
{
    public RealLiteral([Pattern(@"[0-9]+\.[0-9]+")] Token value) { }
}

public sealed class StringLiteral : Expression
{
    public StringLiteral([Pattern(@"""([^""\\]|\\.)*""")] Token value) { }
}

public sealed class CharLiteral : Expression
{
    public CharLiteral([Pattern(@"'([^'\\]|\\.)'")] Token value) { }
}

public sealed class TrueLiteral : Expression
{
    public TrueLiteral([Pattern(@"true", Priority = 1)] Token kw) { }
}

public sealed class FalseLiteral : Expression
{
    public FalseLiteral([Pattern(@"false", Priority = 1)] Token kw) { }
}

public sealed class NullLiteral : Expression
{
    public NullLiteral([Pattern(@"null", Priority = 1)] Token kw) { }
}

public sealed class IdentifierExpr : Expression
{
    public IdentifierExpr([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class ThisExpr : Expression
{
    public ThisExpr([Pattern(@"this", Priority = 1)] Token kw) { }
}

public sealed class ParenExpr : Expression
{
    public ParenExpr([Pattern(@"\(")] Token lp, Expression inner, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed class MemberAccess : Expression
{
    public MemberAccess(Expression target, [Pattern(@"\.")] Token dot, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

[Precedence(15)]
public sealed class Invocation : Expression
{
    public Invocation(Expression target, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed class PostIncrement : Expression
{
    public PostIncrement(Expression operand, [Pattern(@"\+\+")] Token op) { }
}

[Precedence(15)]
public sealed class PostDecrement : Expression
{
    public PostDecrement(Expression operand, [Pattern(@"--")] Token op) { }
}

public abstract class TupleElementList : AstNode { }

public sealed class SingleTupleElementList : TupleElementList
{
    public SingleTupleElementList(Expression head, TupleElementTail tail) { }
}

public abstract class TupleElementTail : AstNode { }

public sealed class NilTupleElementTail : TupleElementTail
{
    public NilTupleElementTail() { }
}

public sealed class ConsTupleElementTail : TupleElementTail
{
    public ConsTupleElementTail([Pattern(@",")] Token sep, Expression head, TupleElementTail tail) { }
}

public abstract class InitializerList : AstNode { }

public sealed class NilInitializerList : InitializerList
{
    public NilInitializerList() { }
}

public sealed class SingleInitializerList : InitializerList
{
    public SingleInitializerList(Expression head, InitializerTail tail) { }
}

public abstract class InitializerTail : AstNode { }

public sealed class NilInitializerTail : InitializerTail
{
    public NilInitializerTail() { }
}

public sealed class ConsInitializerTail : InitializerTail
{
    public ConsInitializerTail([Pattern(@",")] Token sep, Expression head, InitializerTail tail) { }
}

public abstract class CollectionElementList : AstNode { }

public sealed class NilCollectionElementList : CollectionElementList
{
    public NilCollectionElementList() { }
}

public sealed class SingleCollectionElementList : CollectionElementList
{
    public SingleCollectionElementList(Expression head, CollectionElementTail tail) { }
}

public abstract class CollectionElementTail : AstNode { }

public sealed class NilCollectionElementTail : CollectionElementTail
{
    public NilCollectionElementTail() { }
}

public sealed class ConsCollectionElementTail : CollectionElementTail
{
    public ConsCollectionElementTail([Pattern(@",")] Token sep, Expression head, CollectionElementTail tail) { }
}

public abstract class LambdaParameterList : AstNode { }

public sealed class NilLambdaParameterList : LambdaParameterList
{
    public NilLambdaParameterList() { }
}

public sealed class SingleLambdaParameterList : LambdaParameterList
{
    public SingleLambdaParameterList([Pattern(@"[A-Za-z_]\w*")] Token name, LambdaParameterTail tail) { }
}

public abstract class LambdaParameterTail : AstNode { }

public sealed class NilLambdaParameterTail : LambdaParameterTail
{
    public NilLambdaParameterTail() { }
}

public sealed class ConsLambdaParameterTail : LambdaParameterTail
{
    public ConsLambdaParameterTail([Pattern(@",")] Token sep, [Pattern(@"[A-Za-z_]\w*")] Token name, LambdaParameterTail tail) { }
}

public abstract class SwitchExprArmList : AstNode { }

public sealed class NilSwitchExprArmList : SwitchExprArmList
{
    public NilSwitchExprArmList() { }
}

public sealed class SingleSwitchExprArmList : SwitchExprArmList
{
    public SingleSwitchExprArmList(SwitchExprArm arm) { }
}

public sealed class ConsSwitchExprArmList : SwitchExprArmList
{
    public ConsSwitchExprArmList(SwitchExprArm head, [Pattern(@",")] Token sep, SwitchExprArmList rest) { }
}

public abstract class SwitchExprArm : AstNode { }

public sealed class PatternArm : SwitchExprArm
{
    public PatternArm(Pattern pattern, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public sealed class DiscardArm : SwitchExprArm
{
    public DiscardArm([Pattern(@"_")] Token discard, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public abstract class QueryClauseList : AstNode { }

public sealed class SingleQueryClause : QueryClauseList
{
    public SingleQueryClause(QueryClause head) { }
}

public sealed class ConsQueryClauseList : QueryClauseList
{
    public ConsQueryClauseList(QueryClause head, QueryClauseList rest) { }
}

public abstract class QueryClause : AstNode { }

[Precedence(1)]
public sealed class FromClause : QueryClause
{
    public FromClause([Pattern(@"from", Priority = 1)] Token kwFrom, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token kwIn, Expression source) { }
}

[Precedence(1)]
public sealed class SelectClause : QueryClause
{
    public SelectClause([Pattern(@"select", Priority = 1)] Token kwSelect, Expression selector) { }
}

[Precedence(1)]
public sealed class WhereClause : QueryClause
{
    public WhereClause([Pattern(@"where", Priority = 1)] Token kwWhere, Expression condition) { }
}

[Precedence(1)]
public sealed class OrderByClause : QueryClause
{
    public OrderByClause([Pattern(@"orderby", Priority = 1)] Token kwOrderBy, Expression key) { }
}

[Precedence(1)]
public sealed class GroupClause : QueryClause
{
    public GroupClause([Pattern(@"group", Priority = 1)] Token kwGroup, Expression element, [Pattern(@"by", Priority = 1)] Token kwBy, Expression key) { }
}

[Precedence(1)]
public sealed class LetClause : QueryClause
{
    public LetClause([Pattern(@"let", Priority = 1)] Token kwLet, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public sealed class BaseExpr : Expression
{
    public BaseExpr([Pattern(@"base", Priority = 1)] Token kw) { }
}

public sealed class HexLiteral : Expression
{
    public HexLiteral([Pattern(@"0[xX][0-9a-fA-F_]+")] Token value) { }
}

public sealed class BinaryLiteral : Expression
{
    public BinaryLiteral([Pattern(@"0[bB][01_]+")] Token value) { }
}

public sealed class VerbatimStringLiteral : Expression
{
    public VerbatimStringLiteral([Pattern(@"@""(""""|[^""])*""")] Token value) { }
}

public sealed class InterpolatedStringLiteral : Expression
{
    public InterpolatedStringLiteral([Pattern(@"\$\$(""""|[^""])*""")] Token value) { }
}

public sealed class RawStringLiteral : Expression
{
    public RawStringLiteral([Pattern(@"\""""[\s\S]*?\""""")] Token value) { }
}

public sealed class NameofExpr : Expression
{
    public NameofExpr([Pattern(@"nameof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, QualifiedName name, [Pattern(@"\)")] Token rp) { }
}

public sealed class TypeofExpr : Expression
{
    public TypeofExpr([Pattern(@"typeof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp) { }
}

public sealed class SizeofExpr : Expression
{
    public SizeofExpr([Pattern(@"sizeof", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp) { }
}

public sealed class StackallocExpr : Expression
{
    public StackallocExpr([Pattern(@"stackalloc", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb) { }
}

public sealed class TupleExpr : Expression
{
    public TupleExpr([Pattern(@"\(")] Token lp, Expression first, [Pattern(@",")] Token sep, TupleElementList rest, [Pattern(@"\)")] Token rp) { }
}

public sealed class CollectionExpr : Expression
{
    public CollectionExpr([Pattern(@"\[")] Token lb, CollectionElementList elements, [Pattern(@"\]")] Token rb) { }
}

[Precedence(14)]
public sealed class IndexExpr : Expression
{
    public IndexExpr([Pattern(@"\^")] Token hat, Expression expr) { }
}

[Precedence(15)]
public sealed class ElementAccess : Expression
{
    public ElementAccess(Expression target, [Pattern(@"\[")] Token lb, ArgumentList args, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class NullConditionalMember : Expression
{
    public NullConditionalMember(Expression target, [Pattern(@"\?\.")] Token op, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

[Precedence(15)]
public sealed class NullConditionalIndex : Expression
{
    public NullConditionalIndex(Expression target, [Pattern(@"\?\[")] Token op, ArgumentList args, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class RangeExpr : Expression
{
    public RangeExpr(Expression from, [Pattern(@"\.\.")] Token op, Expression to) { }
}

[Precedence(14)]
public sealed class PreIncrementExpr : Expression
{
    public PreIncrementExpr([Pattern(@"\+\+")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed class PreDecrementExpr : Expression
{
    public PreDecrementExpr([Pattern(@"--")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed class IndirectionExpr : Expression
{
    public IndirectionExpr([Pattern(@"\*")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed class AddressOfExpr : Expression
{
    public AddressOfExpr([Pattern(@"&")] Token op, Expression expr) { }
}

[Precedence(14)]
public sealed class CastExpr : Expression
{
    public CastExpr([Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp, Expression expr) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class AssignExpr : Expression
{
    public AssignExpr(Expression left, [Pattern(@"=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class AddAssignExpr : Expression
{
    public AddAssignExpr(Expression left, [Pattern(@"\+=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class SubAssignExpr : Expression
{
    public SubAssignExpr(Expression left, [Pattern(@"-=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class MulAssignExpr : Expression
{
    public MulAssignExpr(Expression left, [Pattern(@"\*=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class DivAssignExpr : Expression
{
    public DivAssignExpr(Expression left, [Pattern(@"/=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class ModAssignExpr : Expression
{
    public ModAssignExpr(Expression left, [Pattern(@"%=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class AndAssignExpr : Expression
{
    public AndAssignExpr(Expression left, [Pattern(@"&=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class OrAssignExpr : Expression
{
    public OrAssignExpr(Expression left, [Pattern(@"\|=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class XorAssignExpr : Expression
{
    public XorAssignExpr(Expression left, [Pattern(@"\^=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class LeftShiftAssignExpr : Expression
{
    public LeftShiftAssignExpr(Expression left, [Pattern(@"<<=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class RightShiftAssignExpr : Expression
{
    public RightShiftAssignExpr(Expression left, [Pattern(@">>=")] Token op, Expression right) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class CoalesceAssignExpr : Expression
{
    public CoalesceAssignExpr(Expression left, [Pattern(@"\?\?=")] Token op, Expression right) { }
}

[Precedence(2, IsRightAssociative = true)]
public sealed class ConditionalExpr : Expression
{
    public ConditionalExpr(Expression cond, [Pattern(@"\?")] Token question, Expression then, [Pattern(@":")] Token colon, Expression elseBranch) { }
}

[Precedence(3)]
public sealed class CoalesceExpr : Expression
{
    public CoalesceExpr(Expression left, [Pattern(@"\?\?")] Token op, Expression right) { }
}

[Precedence(4)]
public sealed class OrExpr : Expression
{
    public OrExpr(Expression left, [Pattern(@"\|\|")] Token op, Expression right) { }
}

[Precedence(5)]
public sealed class AndExpr : Expression
{
    public AndExpr(Expression left, [Pattern(@"&&")] Token op, Expression right) { }
}

[Precedence(6)]
public sealed class BitOrExpr : Expression
{
    public BitOrExpr(Expression left, [Pattern(@"\|")] Token op, Expression right) { }
}

[Precedence(7)]
public sealed class BitXorExpr : Expression
{
    public BitXorExpr(Expression left, [Pattern(@"\^")] Token op, Expression right) { }
}

[Precedence(8)]
public sealed class BitAndExpr : Expression
{
    public BitAndExpr(Expression left, [Pattern(@"&")] Token op, Expression right) { }
}

[Precedence(9)]
public sealed class EqualExpr : Expression
{
    public EqualExpr(Expression left, [Pattern(@"==")] Token op, Expression right) { }
}

[Precedence(9)]
public sealed class NotEqualExpr : Expression
{
    public NotEqualExpr(Expression left, [Pattern(@"!=")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed class LessExpr : Expression
{
    public LessExpr(Expression left, [Pattern(@"<")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed class GreaterExpr : Expression
{
    public GreaterExpr(Expression left, [Pattern(@">")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed class LessEqualExpr : Expression
{
    public LessEqualExpr(Expression left, [Pattern(@"<=")] Token op, Expression right) { }
}

[Precedence(10)]
public sealed class GreaterEqualExpr : Expression
{
    public GreaterEqualExpr(Expression left, [Pattern(@">=")] Token op, Expression right) { }
}

[Precedence(11)]
public sealed class LeftShiftExpr : Expression
{
    public LeftShiftExpr(Expression left, [Pattern(@"<<")] Token op, Expression right) { }
}

[Precedence(11)]
public sealed class RightShiftExpr : Expression
{
    public RightShiftExpr(Expression left, [Pattern(@">>")] Token op, Expression right) { }
}

[Precedence(12)]
public sealed class AddExpr : Expression
{
    public AddExpr(Expression left, [Pattern(@"\+")] Token op, Expression right) { }
}

[Precedence(12)]
public sealed class SubExpr : Expression
{
    public SubExpr(Expression left, [Pattern(@"-")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed class MulExpr : Expression
{
    public MulExpr(Expression left, [Pattern(@"\*")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed class DivExpr : Expression
{
    public DivExpr(Expression left, [Pattern(@"/")] Token op, Expression right) { }
}

[Precedence(13)]
public sealed class ModExpr : Expression
{
    public ModExpr(Expression left, [Pattern(@"%")] Token op, Expression right) { }
}

[Precedence(14)]
public sealed class AwaitExpr : Expression
{
    public AwaitExpr([Pattern(@"await", Priority = 1)] Token kw, Expression expr) { }
}

[Precedence(10)]
public sealed class IsPatternExpr : Expression
{
    public IsPatternExpr(Expression expr, [Pattern(@"is", Priority = 1)] Token kw, Pattern pattern) { }
}

[Precedence(10)]
public sealed class AsExpr : Expression
{
    public AsExpr(Expression expr, [Pattern(@"as", Priority = 1)] Token kw, Type type) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed class SimpleLambdaExpr : Expression
{
    public SimpleLambdaExpr([Pattern(@"[A-Za-z_]\w*")] Token param, [Pattern(@"=>")] Token arrow, Expression body) { }
}

public sealed class AnonymousMethodExpr : Expression
{
    public AnonymousMethodExpr([Pattern(@"delegate", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed class AnonymousMethodParamsExpr : Expression
{
    public AnonymousMethodParamsExpr([Pattern(@"delegate", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, LambdaParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed class ObjectCreationExpr : Expression
{
    public ObjectCreationExpr([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public sealed class ObjectCreationInitExpr : Expression
{
    public ObjectCreationInitExpr([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

public sealed class ObjectCreationEmptyInitExpr : Expression
{
    public ObjectCreationEmptyInitExpr([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

public sealed class ArrayCreationExpr : Expression
{
    public ArrayCreationExpr([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb) { }
}

public sealed class ArrayCreationInitExpr : Expression
{
    public ArrayCreationInitExpr([Pattern(@"new", Priority = 1)] Token kw, Type type, [Pattern(@"\[")] Token lb, Expression size, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lb2, InitializerList initializers, [Pattern(@"\}")] Token rb2) { }
}

public sealed class ImplicitArrayCreationExpr : Expression
{
    public ImplicitArrayCreationExpr([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\[")] Token lb, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lb2, InitializerList initializers, [Pattern(@"\}")] Token rb2) { }
}

public sealed class TargetTypedNewExpr : Expression
{
    public TargetTypedNewExpr([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public sealed class TargetTypedNewInitExpr : Expression
{
    public TargetTypedNewInitExpr([Pattern(@"new", Priority = 1)] Token kw, [Pattern(@"\(")] Token lp, ArgumentList args, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed class WithExpr : Expression
{
    public WithExpr(Expression expr, [Pattern(@"with", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, InitializerList initializers, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed class SwitchExpr : Expression
{
    public SwitchExpr(Expression governor, [Pattern(@"switch", Priority = 1)] Token kw, [Pattern(@"\{")] Token lb, SwitchExprArmList arms, [Pattern(@"\}")] Token rb) { }
}

public sealed class QueryExpr : Expression
{
    public QueryExpr([Pattern(@"from", Priority = 1)] Token kwFrom, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token kwIn, Expression source, QueryClauseList clauses) { }
}

[Precedence(1)]
public sealed class ThrowExpr : Expression
{
    public ThrowExpr([Pattern(@"throw", Priority = 1)] Token kw, Expression expr) { }
}

public abstract class Pattern : AstNode { }

public sealed class NullConstantPattern : Pattern
{
    public NullConstantPattern([Pattern(@"null", Priority = 1)] Token kw) { }
}

public sealed class TrueConstantPattern : Pattern
{
    public TrueConstantPattern([Pattern(@"true", Priority = 1)] Token kw) { }
}

public sealed class FalseConstantPattern : Pattern
{
    public FalseConstantPattern([Pattern(@"false", Priority = 1)] Token kw) { }
}

public sealed class IntConstantPattern : Pattern
{
    public IntConstantPattern([Pattern(@"[0-9]+[dDfFlLmMuU]*")] Token value) { }
}

public sealed class RealConstantPattern : Pattern
{
    public RealConstantPattern([Pattern(@"[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]*")] Token value) { }
}

public sealed class HexConstantPattern : Pattern
{
    public HexConstantPattern([Pattern(@"0[xX][0-9a-fA-F_]+")] Token value) { }
}

public sealed class BinaryConstantPattern : Pattern
{
    public BinaryConstantPattern([Pattern(@"0[bB][01_]+")] Token value) { }
}

public sealed class CharConstantPattern : Pattern
{
    public CharConstantPattern([Pattern(@"'([^'\\]|\\.)'")] Token value) { }
}

public sealed class StringConstantPattern : Pattern
{
    public StringConstantPattern([Pattern(@"""([^""\\]|\\.)*""")] Token value) { }
}

public sealed class TypePattern : Pattern
{
    public TypePattern(Type type) { }
}

public sealed class DeclarationPattern : Pattern
{
    public DeclarationPattern(Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class VarPattern : Pattern
{
    public VarPattern([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class DiscardPattern : Pattern
{
    public DiscardPattern([Pattern(@"_", Priority = 1)] Token underscore) { }
}

[Precedence(15)]
public sealed class ParenPattern : Pattern
{
    public ParenPattern([Pattern(@"\(")] Token lp, Pattern inner, [Pattern(@"\)")] Token rp) { }
}

[Precedence(15)]
public sealed class ListPattern : Pattern
{
    public ListPattern([Pattern(@"\[")] Token lb, ListPatternElemList elements, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class SlicePattern : Pattern
{
    public SlicePattern([Pattern(@"\[")] Token lb, [Pattern(@"\.\.")] Token slice, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class PropertyPattern : Pattern
{
    public PropertyPattern([Pattern(@"\{")] Token lb, PropPatternList properties, [Pattern(@"\}")] Token rb) { }
}

[Precedence(15)]
public sealed class PositionalPattern : Pattern
{
    public PositionalPattern([Pattern(@"\(")] Token lp, Pattern first, [Pattern(@",")] Token comma, PositionalRestList rest, [Pattern(@"\)")] Token rp) { }
}

[Precedence(14)]
public sealed class LessThanPattern : Pattern
{
    public LessThanPattern([Pattern(@"<")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed class GreaterThanPattern : Pattern
{
    public GreaterThanPattern([Pattern(@">")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed class LessThanOrEqualPattern : Pattern
{
    public LessThanOrEqualPattern([Pattern(@"<=")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed class GreaterThanOrEqualPattern : Pattern
{
    public GreaterThanOrEqualPattern([Pattern(@">=")] Token op, Pattern right) { }
}

[Precedence(14)]
public sealed class NotPattern : Pattern
{
    public NotPattern([Pattern(@"not", Priority = 1)] Token notKw, Pattern operand) { }
}

[Precedence(8)]
public sealed class AndPattern : Pattern
{
    public AndPattern(Pattern left, [Pattern(@"and", Priority = 1)] Token andKw, Pattern right) { }
}

[Precedence(6)]
public sealed class OrPattern : Pattern
{
    public OrPattern(Pattern left, [Pattern(@"or", Priority = 1)] Token orKw, Pattern right) { }
}

public abstract class ListPatternElemList : AstNode { }

public sealed class NilListPatternElem : ListPatternElemList
{
    public NilListPatternElem() { }
}

public sealed class SingleListPatternElem : ListPatternElemList
{
    public SingleListPatternElem(Pattern head, ListPatternElemTail tail) { }
}

public abstract class ListPatternElemTail : AstNode { }

public sealed class NilListPatternElemTail : ListPatternElemTail
{
    public NilListPatternElemTail() { }
}

public sealed class ConsListPatternElemTail : ListPatternElemTail
{
    public ConsListPatternElemTail([Pattern(@",")] Token comma, Pattern head, ListPatternElemTail tail) { }
}

public abstract class PositionalRestList : AstNode { }

public sealed class SinglePositionalRest : PositionalRestList
{
    public SinglePositionalRest(Pattern head, PositionalRestTail tail) { }
}

public abstract class PositionalRestTail : AstNode { }

public sealed class NilPositionalRestTail : PositionalRestTail
{
    public NilPositionalRestTail() { }
}

public sealed class ConsPositionalRestTail : PositionalRestTail
{
    public ConsPositionalRestTail([Pattern(@",")] Token comma, Pattern head, PositionalRestTail tail) { }
}

public abstract class PropPatternList : AstNode { }

public sealed class NilPropPatternList : PropPatternList
{
    public NilPropPatternList() { }
}

public sealed class SinglePropPattern : PropPatternList
{
    public SinglePropPattern([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Pattern value) { }
}

public sealed class ConsPropPattern : PropPatternList
{
    public ConsPropPattern(PropPatternList list, [Pattern(@",")] Token comma, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Pattern value) { }
}

public abstract class Statement : AstNode { }

public sealed class EmptyStatement : Statement
{
    public EmptyStatement([Pattern(@";")] Token semi) { }
}

public sealed class ExpressionStatement : Statement
{
    public ExpressionStatement(Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class VarDeclaration : Statement
{
    public VarDeclaration([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed class LocalConstantDeclaration : Statement
{
    public LocalConstantDeclaration([Pattern(@"const", Priority = 1)] Token constKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed class IfStatement : Statement
{
    public IfStatement([Pattern(@"if", Priority = 1)] Token ifKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement then) { }
}

public sealed class IfElseStatement : Statement
{
    public IfElseStatement([Pattern(@"if", Priority = 1)] Token ifKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement then, [Pattern(@"else", Priority = 1)] Token elseKw, Statement elseBranch) { }
}

public sealed class WhileStatement : Statement
{
    public WhileStatement([Pattern(@"while", Priority = 1)] Token whileKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ReturnStatement : Statement
{
    public ReturnStatement([Pattern(@"return", Priority = 1)] Token returnKw, [Pattern(@";")] Token semi) { }
}

public sealed class ReturnExprStatement : Statement
{
    public ReturnExprStatement([Pattern(@"return", Priority = 1)] Token returnKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class BreakStatement : Statement
{
    public BreakStatement([Pattern(@"break", Priority = 1)] Token breakKw, [Pattern(@";")] Token semi) { }
}

public sealed class ContinueStatement : Statement
{
    public ContinueStatement([Pattern(@"continue", Priority = 1)] Token continueKw, [Pattern(@";")] Token semi) { }
}

public sealed class BlockStatement : Statement
{
    public BlockStatement([Pattern(@"\{")] Token lb, [Pattern(@"\}")] Token rb) { }
}

public sealed class BlockStatementWithBody : Statement
{
    public BlockStatementWithBody([Pattern(@"\{")] Token lb, StatementList body, [Pattern(@"\}")] Token rb) { }
}

public abstract class StatementList : AstNode { }

public sealed class SingleStatement : StatementList
{
    public SingleStatement(Statement head) { }
}

public sealed class ConsStatement : StatementList
{
    public ConsStatement(Statement head, StatementList rest) { }
}

public abstract class SwitchSectionStatementList : AstNode { }

public sealed class SingleSwitchSectionStatement : SwitchSectionStatementList
{
    public SingleSwitchSectionStatement(Statement head) { }
}

public sealed class ConsSwitchSectionStatement : SwitchSectionStatementList
{
    public ConsSwitchSectionStatement(Statement head, SwitchSectionStatementList rest) { }
}

public abstract class ForInit : AstNode { }

public sealed class NilForInit : ForInit
{
    public NilForInit() { }
}

public sealed class ForInitVar : ForInit
{
    public ForInitVar([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init) { }
}

public sealed class ForInitExprList : ForInit
{
    public ForInitExprList(Expression head, ForInitExprTail tail) { }
}

public abstract class ForInitExprTail : AstNode { }

public sealed class NilForInitExprTail : ForInitExprTail
{
    public NilForInitExprTail() { }
}

public sealed class ConsForInitExprTail : ForInitExprTail
{
    public ConsForInitExprTail([Pattern(@",")] Token comma, Expression head, ForInitExprTail tail) { }
}

public abstract class ForUpdate : AstNode { }

public sealed class NilForUpdate : ForUpdate
{
    public NilForUpdate() { }
}

public sealed class ForUpdateExprList : ForUpdate
{
    public ForUpdateExprList(Expression head, ForUpdateExprTail tail) { }
}

public abstract class ForUpdateExprTail : AstNode { }

public sealed class NilForUpdateExprTail : ForUpdateExprTail
{
    public NilForUpdateExprTail() { }
}

public sealed class ConsForUpdateExprTail : ForUpdateExprTail
{
    public ConsForUpdateExprTail([Pattern(@",")] Token comma, Expression head, ForUpdateExprTail tail) { }
}

public abstract class ForCondition : AstNode { }

public sealed class NilForCondition : ForCondition
{
    public NilForCondition() { }
}

public sealed class ForConditionExpr : ForCondition
{
    public ForConditionExpr(Expression cond) { }
}

public sealed class ForStatement : Statement
{
    public ForStatement([Pattern(@"for", Priority = 1)] Token forKw, [Pattern(@"\(")] Token lp, ForInit init, [Pattern(@";")] Token semi1, ForCondition cond, [Pattern(@";")] Token semi2, ForUpdate update, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ForEachStatement : Statement
{
    public ForEachStatement([Pattern(@"foreach", Priority = 1)] Token foreachKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token inKw, Expression collection, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ForEachVarStatement : Statement
{
    public ForEachVarStatement([Pattern(@"foreach", Priority = 1)] Token foreachKw, [Pattern(@"\(")] Token lp, [Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"in", Priority = 1)] Token inKw, Expression collection, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class DoStatement : Statement
{
    public DoStatement([Pattern(@"do", Priority = 1)] Token doKw, Statement body, [Pattern(@"while", Priority = 1)] Token whileKw, [Pattern(@"\(")] Token lp, Expression cond, [Pattern(@"\)")] Token rp, [Pattern(@";")] Token semi) { }
}

public abstract class CaseLabel : AstNode { }

public sealed class CaseExprLabel : CaseLabel
{
    public CaseExprLabel([Pattern(@"case", Priority = 1)] Token caseKw, Expression value, [Pattern(@":")] Token colon) { }
}

public sealed class DefaultLabel : CaseLabel
{
    public DefaultLabel([Pattern(@"default", Priority = 1)] Token defaultKw, [Pattern(@":")] Token colon) { }
}

public abstract class CaseLabelList : AstNode { }

public sealed class SingleCaseLabel : CaseLabelList
{
    public SingleCaseLabel(CaseLabel head) { }
}

public sealed class ConsCaseLabel : CaseLabelList
{
    public ConsCaseLabel(CaseLabelList list, CaseLabel label) { }
}

public abstract class SwitchSection : AstNode { }

public sealed class LabeledSwitchSection : SwitchSection
{
    public LabeledSwitchSection(CaseLabelList labels, SwitchSectionStatementList body) { }
}

public abstract class SwitchSectionList : AstNode { }

public sealed class NilSwitchSection : SwitchSectionList
{
    public NilSwitchSection() { }
}

public sealed class ConsSwitchSection : SwitchSectionList
{
    public ConsSwitchSection(SwitchSection head, SwitchSectionList rest) { }
}

public sealed class SwitchStatement : Statement
{
    public SwitchStatement([Pattern(@"switch", Priority = 1)] Token switchKw, [Pattern(@"\(")] Token lp, Expression expr, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, SwitchSectionList sections, [Pattern(@"\}")] Token rb) { }
}

public abstract class CatchClause : AstNode { }

public sealed class CatchTypeClause : CatchClause
{
    public CatchTypeClause([Pattern(@"catch", Priority = 1)] Token catchKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class CatchTypeOnlyClause : CatchClause
{
    public CatchTypeOnlyClause([Pattern(@"catch", Priority = 1)] Token catchKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class CatchGeneralClause : CatchClause
{
    public CatchGeneralClause([Pattern(@"catch", Priority = 1)] Token catchKw, Statement body) { }
}

public abstract class CatchClauseList : AstNode { }

public sealed class NilCatchClause : CatchClauseList
{
    public NilCatchClause() { }
}

public sealed class ConsCatchClause : CatchClauseList
{
    public ConsCatchClause(CatchClause head, CatchClauseList rest) { }
}

public abstract class FinallyClause : AstNode { }

public sealed class NilFinallyClause : FinallyClause
{
    public NilFinallyClause() { }
}

public sealed class PresentFinallyClause : FinallyClause
{
    public PresentFinallyClause([Pattern(@"finally", Priority = 1)] Token finallyKw, Statement body) { }
}

public sealed class TryStatement : Statement
{
    public TryStatement([Pattern(@"try", Priority = 1)] Token tryKw, Statement body, CatchClauseList catchClauses, FinallyClause finallyClause) { }
}

public sealed class LockStatement : Statement
{
    public LockStatement([Pattern(@"lock", Priority = 1)] Token lockKw, [Pattern(@"\(")] Token lp, Expression expr, [Pattern(@"\)")] Token rp, Statement body) { }
}

public abstract class UsingResource : AstNode { }

public sealed class UsingExprResource : UsingResource
{
    public UsingExprResource(Expression expr) { }
}

public sealed class UsingVarResource : UsingResource
{
    public UsingVarResource([Pattern(@"var", Priority = 1)] Token varKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init) { }
}

public sealed class UsingStatement : Statement
{
    public UsingStatement([Pattern(@"using", Priority = 1)] Token usingKw, [Pattern(@"\(")] Token lp, UsingResource resource, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class FixedStatement : Statement
{
    public FixedStatement([Pattern(@"fixed", Priority = 1)] Token fixedKw, [Pattern(@"\(")] Token lp, Type type, [Pattern(@"\*")] Token star, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class CheckedStatement : Statement
{
    public CheckedStatement([Pattern(@"checked", Priority = 1)] Token checkedKw, Statement body) { }
}

public sealed class UncheckedStatement : Statement
{
    public UncheckedStatement([Pattern(@"unchecked", Priority = 1)] Token uncheckedKw, Statement body) { }
}

public sealed class UnsafeStatement : Statement
{
    public UnsafeStatement([Pattern(@"unsafe", Priority = 1)] Token unsafeKw, Statement body) { }
}

public sealed class YieldReturnStatement : Statement
{
    public YieldReturnStatement([Pattern(@"yield", Priority = 1)] Token yieldKw, [Pattern(@"return", Priority = 1)] Token returnKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class YieldBreakStatement : Statement
{
    public YieldBreakStatement([Pattern(@"yield", Priority = 1)] Token yieldKw, [Pattern(@"break", Priority = 1)] Token breakKw, [Pattern(@";")] Token semi) { }
}

public sealed class GotoStatement : Statement
{
    public GotoStatement([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed class GotoCaseStatement : Statement
{
    public GotoCaseStatement([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"case", Priority = 1)] Token caseKw, Expression value, [Pattern(@";")] Token semi) { }
}

public sealed class GotoDefaultStatement : Statement
{
    public GotoDefaultStatement([Pattern(@"goto", Priority = 1)] Token gotoKw, [Pattern(@"default", Priority = 1)] Token defaultKw, [Pattern(@";")] Token semi) { }
}

public sealed class LabeledStatement : Statement
{
    public LabeledStatement([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@":")] Token colon, Statement body) { }
}

public sealed class ThrowStatement : Statement
{
    public ThrowStatement([Pattern(@"throw", Priority = 1)] Token throwKw, [Pattern(@";")] Token semi) { }
}

public sealed class ThrowExprStatement : Statement
{
    public ThrowExprStatement([Pattern(@"throw", Priority = 1)] Token throwKw, Expression expr, [Pattern(@";")] Token semi) { }
}

public abstract class QualifiedName : AstNode { }

public sealed class SimpleQualifiedName : QualifiedName
{
    public SimpleQualifiedName([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class QualifiedQualifiedName : QualifiedName
{
    public QualifiedQualifiedName(QualifiedName left, [Pattern(@"\.")] Token dot, [Pattern(@"[A-Za-z_]\w*")] Token right) { }
}

public abstract class ModifierList : AstNode { }

public sealed class NilModifierList : ModifierList
{
    public NilModifierList() { }
}

public sealed class ConsModifier : ModifierList
{
    public ConsModifier([Pattern(@"(public|private|protected|internal|static|readonly|abstract|sealed|const|async|virtual|override|extern|partial|unsafe|volatile)", Priority = 1)] Token modifier, ModifierList rest) { }
}

public abstract class Declaration : AstNode { }

public sealed class UsingDirective : Declaration
{
    public UsingDirective([Pattern(@"using", Priority = 1)] Token usingKw, QualifiedName ns, [Pattern(@";")] Token semi) { }
}

public sealed class NamespaceDeclaration : Declaration
{
    public NamespaceDeclaration([Pattern(@"namespace", Priority = 1)] Token namespaceKw, QualifiedName name, [Pattern(@"\{")] Token lb, NamespaceBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class ClassDeclaration : Declaration
{
    public ClassDeclaration(ModifierList modifiers, [Pattern(@"class", Priority = 1)] Token classKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public abstract class NamespaceBody : AstNode { }

public sealed class NilNamespaceBody : NamespaceBody
{
    public NilNamespaceBody() { }
}

public sealed class ConsNamespaceMember : NamespaceBody
{
    public ConsNamespaceMember(Declaration head, NamespaceBody rest) { }
}

public abstract class TypeParameter : AstNode { }

public sealed class PlainTypeParameter : TypeParameter
{
    public PlainTypeParameter([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public abstract class TypeParameterList : AstNode { }

public sealed class SingleTypeParameter : TypeParameterList
{
    public SingleTypeParameter([Pattern(@"<")] Token lt, TypeParameter head) { }
}

public sealed class ConsTypeParameter : TypeParameterList
{
    public ConsTypeParameter(TypeParameterList list, [Pattern(@",")] Token comma, TypeParameter next) { }
}

public abstract class OptionalTypeParameterList : AstNode { }

public sealed class AbsentTypeParameterList : OptionalTypeParameterList
{
    public AbsentTypeParameterList() { }
}

public sealed class PresentTypeParameterList : OptionalTypeParameterList
{
    public PresentTypeParameterList(TypeParameterList list, [Pattern(@">")] Token gt) { }
}

public abstract class BaseList : AstNode { }

public sealed class NilBaseList : BaseList
{
    public NilBaseList() { }
}

public sealed class SingleBaseType : BaseList
{
    public SingleBaseType([Pattern(@":")] Token colon, Type head) { }
}

public sealed class ConsBaseType : BaseList
{
    public ConsBaseType(BaseList list, [Pattern(@",")] Token comma, Type next) { }
}

public abstract class TypeParameterConstraint : AstNode { }

public sealed class ClassTypeConstraint : TypeParameterConstraint
{
    public ClassTypeConstraint([Pattern(@"class", Priority = 1)] Token kw) { }
}

public sealed class StructTypeConstraint : TypeParameterConstraint
{
    public StructTypeConstraint([Pattern(@"struct", Priority = 1)] Token kw) { }
}

public sealed class TypeConstraint : TypeParameterConstraint
{
    public TypeConstraint(Type type) { }
}

public abstract class TypeParameterConstraintList : AstNode { }

public sealed class SingleTypeParameterConstraint : TypeParameterConstraintList
{
    public SingleTypeParameterConstraint(TypeParameterConstraint head) { }
}

public sealed class ConsTypeParameterConstraint : TypeParameterConstraintList
{
    public ConsTypeParameterConstraint(TypeParameterConstraintList list, [Pattern(@",")] Token comma, TypeParameterConstraint next) { }
}

public abstract class TypeParameterConstraintClauseList : AstNode { }

public sealed class NilTypeParameterConstraintClause : TypeParameterConstraintClauseList
{
    public NilTypeParameterConstraintClause() { }
}

public sealed class ConsTypeParameterConstraintClause : TypeParameterConstraintClauseList
{
    public ConsTypeParameterConstraintClause([Pattern(@"where", Priority = 1)] Token whereKw, [Pattern(@"[A-Za-z_]\w*")] Token param, [Pattern(@":")] Token colon, TypeParameterConstraintList constraints, TypeParameterConstraintClauseList rest) { }
}

public sealed class StructDeclaration : Declaration
{
    public StructDeclaration(ModifierList modifiers, [Pattern(@"struct", Priority = 1)] Token structKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class InterfaceDeclaration : Declaration
{
    public InterfaceDeclaration(ModifierList modifiers, [Pattern(@"interface", Priority = 1)] Token interfaceKw, [Pattern(@"[A-Za-z_]\w*")] Token name, OptionalTypeParameterList typeParams, BaseList bases, TypeParameterConstraintClauseList constraints, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class EnumDeclaration : Declaration
{
    public EnumDeclaration(ModifierList modifiers, [Pattern(@"enum", Priority = 1)] Token enumKw, [Pattern(@"[A-Za-z_]\w*")] Token name, BaseList bases, [Pattern(@"\{")] Token lb, EnumMemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class DelegateDeclaration : Declaration
{
    public DelegateDeclaration(ModifierList modifiers, [Pattern(@"delegate", Priority = 1)] Token delegateKw, Type returnType, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@";")] Token semi) { }
}

public sealed class RecordDeclaration : Declaration
{
    public RecordDeclaration(ModifierList modifiers, [Pattern(@"record", Priority = 1)] Token recordKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, BaseList bases, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class RecordStructDeclaration : Declaration
{
    public RecordStructDeclaration(ModifierList modifiers, [Pattern(@"record", Priority = 1)] Token recordKw, [Pattern(@"struct", Priority = 1)] Token structKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@"\{")] Token lb, MemberBody body, [Pattern(@"\}")] Token rb) { }
}

public sealed class FileScopedNamespaceDeclaration : Declaration
{
    public FileScopedNamespaceDeclaration([Pattern(@"namespace", Priority = 1)] Token namespaceKw, QualifiedName name, [Pattern(@";")] Token semi) { }
}

public sealed class GlobalUsingDirective : Declaration
{
    public GlobalUsingDirective([Pattern(@"global", Priority = 1)] Token globalKw, [Pattern(@"using", Priority = 1)] Token usingKw, QualifiedName ns, [Pattern(@";")] Token semi) { }
}

public sealed class GlobalUsingAliasDirective : Declaration
{
    public GlobalUsingAliasDirective([Pattern(@"global", Priority = 1)] Token globalKw, [Pattern(@"using", Priority = 1)] Token usingKw, [Pattern(@"[A-Za-z_]\w*")] Token alias, [Pattern(@"=")] Token eq, Type target, [Pattern(@";")] Token semi) { }
}

public sealed class ExternAliasDirective : Declaration
{
    public ExternAliasDirective([Pattern(@"extern", Priority = 1)] Token externKw, [Pattern(@"alias", Priority = 1)] Token aliasKw, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public abstract class EnumMemberBody : AstNode { }

public sealed class NilEnumMember : EnumMemberBody
{
    public NilEnumMember() { }
}

public sealed class SingleEnumMember : EnumMemberBody
{
    public SingleEnumMember(EnumMember head) { }
}

public sealed class ConsEnumMember : EnumMemberBody
{
    public ConsEnumMember(EnumMember head, [Pattern(@",")] Token comma, EnumMemberBody rest) { }
}

public abstract class EnumMember : AstNode { }

public sealed class EnumMemberDecl : EnumMember
{
    public EnumMemberDecl([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class EnumMemberInitDecl : EnumMember
{
    public EnumMemberInitDecl([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public abstract class ParameterList : AstNode { }

public sealed class NilParameterList : ParameterList
{
    public NilParameterList() { }
}

public sealed class SingleParameter : ParameterList
{
    public SingleParameter(Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed class ConsParameter : ParameterList
{
    public ConsParameter(ParameterList list, [Pattern(@",")] Token comma, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public abstract class AccessorList : AstNode { }

public sealed class NilAccessorList : AccessorList
{
    public NilAccessorList() { }
}

public sealed class ConsAccessor : AccessorList
{
    public ConsAccessor(Accessor head, AccessorList rest) { }
}

public abstract class Accessor : AstNode { }

public sealed class GetAccessor : Accessor
{
    public GetAccessor([Pattern(@"get", Priority = 1)] Token kw, Statement body) { }
}

public sealed class GetAccessorExprBody : Accessor
{
    public GetAccessorExprBody([Pattern(@"get", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class SetAccessor : Accessor
{
    public SetAccessor([Pattern(@"set", Priority = 1)] Token kw, Statement body) { }
}

public sealed class SetAccessorExprBody : Accessor
{
    public SetAccessorExprBody([Pattern(@"set", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class InitAccessor : Accessor
{
    public InitAccessor([Pattern(@"init", Priority = 1)] Token kw, Statement body) { }
}

public sealed class InitAccessorExprBody : Accessor
{
    public InitAccessorExprBody([Pattern(@"init", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class AddAccessor : Accessor
{
    public AddAccessor([Pattern(@"add", Priority = 1)] Token kw, Statement body) { }
}

public sealed class AddAccessorExprBody : Accessor
{
    public AddAccessorExprBody([Pattern(@"add", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public sealed class RemoveAccessor : Accessor
{
    public RemoveAccessor([Pattern(@"remove", Priority = 1)] Token kw, Statement body) { }
}

public sealed class RemoveAccessorExprBody : Accessor
{
    public RemoveAccessorExprBody([Pattern(@"remove", Priority = 1)] Token kw, [Pattern(@"=>")] Token arrow, Expression expr, [Pattern(@";")] Token semi) { }
}

public abstract class MemberDeclaration : AstNode { }

public sealed class FieldDeclaration : MemberDeclaration
{
    public FieldDeclaration(ModifierList modifiers, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed class MethodDeclaration : MemberDeclaration
{
    public MethodDeclaration(ModifierList modifiers, Type returnType, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class PropertyDeclaration : MemberDeclaration
{
    public PropertyDeclaration(ModifierList modifiers, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\{")] Token lb, AccessorList accessors, [Pattern(@"\}")] Token rb) { }
}

public sealed class IndexerDeclaration : MemberDeclaration
{
    public IndexerDeclaration(ModifierList modifiers, Type type, [Pattern(@"this", Priority = 1)] Token thisKw, [Pattern(@"\[")] Token lb, ParameterList parameters, [Pattern(@"\]")] Token rb, [Pattern(@"\{")] Token lbrace, AccessorList accessors, [Pattern(@"\}")] Token rbrace) { }
}

public sealed class EventDeclaration : MemberDeclaration
{
    public EventDeclaration(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\{")] Token lb, AccessorList accessors, [Pattern(@"\}")] Token rb) { }
}

public sealed class EventFieldDeclaration : MemberDeclaration
{
    public EventFieldDeclaration(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@";")] Token semi) { }
}

public sealed class EventFieldWithInitDeclaration : MemberDeclaration
{
    public EventFieldWithInitDeclaration(ModifierList modifiers, [Pattern(@"event", Priority = 1)] Token eventKw, Type type, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression init, [Pattern(@";")] Token semi) { }
}

public sealed class ImplicitOperatorDeclaration : MemberDeclaration
{
    public ImplicitOperatorDeclaration(ModifierList modifiers, [Pattern(@"implicit", Priority = 1)] Token implicitKw, [Pattern(@"operator", Priority = 1)] Token operatorKw, Type targetType, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ExplicitOperatorDeclaration : MemberDeclaration
{
    public ExplicitOperatorDeclaration(ModifierList modifiers, [Pattern(@"explicit", Priority = 1)] Token explicitKw, [Pattern(@"operator", Priority = 1)] Token operatorKw, Type targetType, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ConstructorDeclaration : MemberDeclaration
{
    public ConstructorDeclaration(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class ConstructorWithInitializerDeclaration : MemberDeclaration
{
    public ConstructorWithInitializerDeclaration(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, ParameterList parameters, [Pattern(@"\)")] Token rp, [Pattern(@":")] Token colon, [Pattern(@"base", Priority = 1)] Token baseKw, [Pattern(@"\(")] Token initLp, ArgumentList args, [Pattern(@"\)")] Token initRp, Statement body) { }
}

public sealed class StaticConstructorDeclaration : MemberDeclaration
{
    public StaticConstructorDeclaration(ModifierList modifiers, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, [Pattern(@"\)")] Token rp, Statement body) { }
}

public sealed class FinalizerDeclaration : MemberDeclaration
{
    public FinalizerDeclaration([Pattern(@"~")] Token tilde, [Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"\(")] Token lp, [Pattern(@"\)")] Token rp, Statement body) { }
}

public abstract class MemberBody : AstNode { }

public sealed class NilMemberBody : MemberBody
{
    public NilMemberBody() { }
}

public sealed class ConsMemberDecl : MemberBody
{
    public ConsMemberDecl(MemberDeclaration head, MemberBody rest) { }
}

public abstract class AttributeSectionList : AstNode { }

public sealed class NilAttributeSection : AttributeSectionList
{
    public NilAttributeSection() { }
}

public sealed class ConsAttributeSection : AttributeSectionList
{
    public ConsAttributeSection(AttributeSection head, AttributeSectionList rest) { }
}

public abstract class AttributeSection : AstNode { }

public sealed class AttributeSectionNoTarget : AttributeSection
{
    public AttributeSectionNoTarget([Pattern(@"\[")] Token lb, AttributeList attributes, [Pattern(@"\]")] Token rb) { }
}

[Precedence(15)]
public sealed class AttributeSectionWithTarget : AttributeSection
{
    public AttributeSectionWithTarget([Pattern(@"\[")] Token lb, [Pattern(@"[A-Za-z_]\w*")] Token target, [Pattern(@":")] Token colon, AttributeList attributes, [Pattern(@"\]")] Token rb) { }
}

public abstract class AttributeList : AstNode { }

public sealed class SingleAttribute : AttributeList
{
    public SingleAttribute(Attribute head) { }
}

public sealed class ConsAttribute : AttributeList
{
    public ConsAttribute(AttributeList list, [Pattern(@",")] Token comma, Attribute head) { }
}

public abstract class Attribute : AstNode { }

public sealed class AttributeDecl : Attribute
{
    public AttributeDecl(QualifiedName name) { }
}

public sealed class AttributeDeclWithArgs : Attribute
{
    public AttributeDeclWithArgs(QualifiedName name, [Pattern(@"\(")] Token lp, AttributeArgumentList args, [Pattern(@"\)")] Token rp) { }
}

public abstract class AttributeArgumentList : AstNode { }

public sealed class NilAttributeArgument : AttributeArgumentList
{
    public NilAttributeArgument() { }
}

public sealed class ConsAttributeArgument : AttributeArgumentList
{
    public ConsAttributeArgument(AttributeArgumentList list, [Pattern(@",")] Token comma, AttributeArg arg) { }
}

public sealed class SingleAttributeArgument : AttributeArgumentList
{
    public SingleAttributeArgument(AttributeArg arg) { }
}

public abstract class AttributeArg : AstNode { }

public sealed class PositionalAttributeArg : AttributeArg
{
    public PositionalAttributeArg(Expression value) { }
}

[Precedence(15)]
public sealed class NamedAttributeArg : AttributeArg
{
    public NamedAttributeArg([Pattern(@"[A-Za-z_]\w*")] Token name, [Pattern(@"=")] Token eq, Expression value) { }
}

public abstract class PPDirective : AstNode { }

public abstract class PPExpr : AstNode { }

public sealed class PPSymbolExpr : PPExpr
{
    public PPSymbolExpr([Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

[Precedence(14)]
public sealed class PPNotExpr : PPExpr
{
    public PPNotExpr([Pattern(@"!")] Token bang, PPExpr operand) { }
}

[Precedence(9)]
public sealed class PPEqExpr : PPExpr
{
    public PPEqExpr(PPExpr left, [Pattern(@"==")] Token op, PPExpr right) { }
}

[Precedence(9)]
public sealed class PPNeExpr : PPExpr
{
    public PPNeExpr(PPExpr left, [Pattern(@"!=")] Token op, PPExpr right) { }
}

[Precedence(5)]
public sealed class PPAndExpr : PPExpr
{
    public PPAndExpr(PPExpr left, [Pattern(@"&&")] Token op, PPExpr right) { }
}

[Precedence(4)]
public sealed class PPOrExpr : PPExpr
{
    public PPOrExpr(PPExpr left, [Pattern(@"\|\|")] Token op, PPExpr right) { }
}

public sealed class PPParenExpr : PPExpr
{
    public PPParenExpr([Pattern(@"\(")] Token lp, PPExpr inner, [Pattern(@"\)")] Token rp) { }
}

public sealed class PPDefine : PPDirective
{
    public PPDefine([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"define", Priority = 1)] Token kwDefine, [Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

public sealed class PPUndef : PPDirective
{
    public PPUndef([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"undef", Priority = 1)] Token kwUndef, [Pattern(@"[A-Za-z_]\w*")] Token symbol) { }
}

public sealed class PPIf : PPDirective
{
    public PPIf([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"if", Priority = 1)] Token kwIf, PPExpr condition) { }
}

public sealed class PPElif : PPDirective
{
    public PPElif([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"elif", Priority = 1)] Token kwElif, PPExpr condition) { }
}

public sealed class PPElse : PPDirective
{
    public PPElse([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"else", Priority = 1)] Token kwElse) { }
}

public sealed class PPEndIf : PPDirective
{
    public PPEndIf([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"endif", Priority = 1)] Token kwEndif) { }
}

public sealed class PPRegion : PPDirective
{
    public PPRegion([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"region", Priority = 1)] Token kwRegion, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPEndRegion : PPDirective
{
    public PPEndRegion([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"endregion", Priority = 1)] Token kwEndregion, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPPragmaWarning : PPDirective
{
    public PPPragmaWarning([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"pragma", Priority = 1)] Token kwPragma, [Pattern(@"warning", Priority = 1)] Token kwWarning, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPPragmaChecksum : PPDirective
{
    public PPPragmaChecksum([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"pragma", Priority = 1)] Token kwPragma, [Pattern(@"checksum", Priority = 1)] Token kwChecksum, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPLine : PPDirective
{
    public PPLine([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"line", Priority = 1)] Token kwLine, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPNullableEnable : PPDirective
{
    public PPNullableEnable([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"enable", Priority = 1)] Token kwEnable) { }
}

public sealed class PPNullableDisable : PPDirective
{
    public PPNullableDisable([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"disable", Priority = 1)] Token kwDisable) { }
}

public sealed class PPNullableWarnings : PPDirective
{
    public PPNullableWarnings([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"warnings", Priority = 1)] Token kwWarnings) { }
}

public sealed class PPNullableAnnotations : PPDirective
{
    public PPNullableAnnotations([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"nullable", Priority = 1)] Token kwNullable, [Pattern(@"annotations", Priority = 1)] Token kwAnnotations) { }
}

public sealed class PPError : PPDirective
{
    public PPError([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"error", Priority = 1)] Token kwError, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class PPWarning : PPDirective
{
    public PPWarning([Pattern(@"#", Priority = 1)] Token hash, [Pattern(@"warning", Priority = 1)] Token kwWarning2, [Pattern(@"[A-Za-z_]\w*")] Token text) { }
}

public sealed class ConsPP : CSharpCompilationUnit
{
    public ConsPP(PPDirective directive, CSharpCompilationUnit rest) { }
}

public sealed class NilCompilationUnit : CSharpCompilationUnit
{
    public NilCompilationUnit() { }
}

public sealed class ConsDeclaration : CSharpCompilationUnit
{
    public ConsDeclaration(Declaration head, CSharpCompilationUnit rest) { }
}

