// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfMegaLang;

[Grammar]
[Skip(@"(\s|//[^\n]*)+")]
public abstract partial class MegaProgram : AstNode { }

public sealed partial class ConsStmt : MegaProgram
{
    [Rule]
    public static void Reduce(Stmt first, MegaProgram rest) { }
}

public sealed partial class NilProgram : MegaProgram
{
    [Rule]
    public static void Reduce() { }
}

public abstract partial class Stmt : AstNode { }

public sealed partial class DeclStmt0 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl0", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt1 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl1", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt2 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl2", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt3 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl3", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt4 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl4", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt5 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl5", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt6 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl6", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt7 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl7", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt8 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl8", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt9 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl9", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt10 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl10", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt11 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl11", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt12 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl12", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt13 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl13", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt14 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl14", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt15 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl15", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt16 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl16", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt17 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl17", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt18 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl18", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt19 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl19", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt20 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl20", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt21 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl21", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt22 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl22", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt23 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl23", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt24 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl24", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt25 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl25", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt26 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl26", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt27 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl27", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt28 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl28", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class DeclStmt29 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"decl29", Priority = 1)] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class ExprStmt : Stmt
{
    [Rule]
    public static void Reduce(Expr expr, [Pattern(@";")] Token semi) { }
}

public sealed partial class IfStmt : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"if", Priority = 2)] Token kwIf, [Pattern(@"\(")] Token lp, Expr cond, [Pattern(@"\)")] Token rp, Stmt body) { }
}

public sealed partial class WhileStmt : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"while", Priority = 2)] Token kwWhile, [Pattern(@"\(")] Token lp, Expr cond, [Pattern(@"\)")] Token rp, Stmt body) { }
}

public sealed partial class BlockStmt : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"\{")] Token lb, MegaProgram body, [Pattern(@"\}")] Token rb) { }
}

public abstract partial class Expr : AstNode { }

public sealed partial class NumExpr : Expr
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+")] Token num) { }
}

public sealed partial class VarExpr : Expr
{
    [Rule]
    public static void Reduce([Pattern(@"[A-Za-z_]\w*")] Token name) { }
}

public sealed partial class ParenExpr : Expr
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, Expr inner, [Pattern(@"\)")] Token rp) { }
}

[Precedence(1, IsRightAssociative = true)]
public sealed partial class AssignExpr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"=")] Token op, Expr right) { }
}

[Precedence(2)]
public sealed partial class Op2Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\+")] Token op, Expr right) { }
}

[Precedence(3)]
public sealed partial class Op3Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"-")] Token op, Expr right) { }
}

[Precedence(4)]
public sealed partial class Op4Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\*")] Token op, Expr right) { }
}

[Precedence(5)]
public sealed partial class Op5Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"/")] Token op, Expr right) { }
}

[Precedence(6)]
public sealed partial class Op6Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"%")] Token op, Expr right) { }
}

[Precedence(7)]
public sealed partial class Op7Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"&")] Token op, Expr right) { }
}

[Precedence(8)]
public sealed partial class Op8Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\|")] Token op, Expr right) { }
}

[Precedence(9)]
public sealed partial class Op9Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\^")] Token op, Expr right) { }
}

[Precedence(10)]
public sealed partial class Op10Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"<")] Token op, Expr right) { }
}

[Precedence(11)]
public sealed partial class Op11Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@">")] Token op, Expr right) { }
}

[Precedence(12)]
public sealed partial class Op12Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"~")] Token op, Expr right) { }
}

[Precedence(13)]
public sealed partial class Op13Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"!")] Token op, Expr right) { }
}

[Precedence(14)]
public sealed partial class Op14Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"@")] Token op, Expr right) { }
}

[Precedence(15)]
public sealed partial class Op15Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"#")] Token op, Expr right) { }
}

[Precedence(16)]
public sealed partial class Op16Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\$")] Token op, Expr right) { }
}

[Precedence(17)]
public sealed partial class Op17Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"\?")] Token op, Expr right) { }
}

[Precedence(18)]
public sealed partial class Op18Expr : Expr
{
    [Rule]
    public static void Reduce(Expr left, [Pattern(@"`")] Token op, Expr right) { }
}

