// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfDeepPrec;

[Grammar]
[Skip(@"\s+")]
public abstract partial class PrecExpr : AstNode { }

public sealed partial class NumExpr : PrecExpr
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+")] Token num) { }
}

[Precedence(1)]
public sealed partial class Op1Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\+")] Token op, PrecExpr right) { }
}

[Precedence(2)]
public sealed partial class Op2Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"-")] Token op, PrecExpr right) { }
}

[Precedence(3)]
public sealed partial class Op3Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\*")] Token op, PrecExpr right) { }
}

[Precedence(4)]
public sealed partial class Op4Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"/")] Token op, PrecExpr right) { }
}

[Precedence(5)]
public sealed partial class Op5Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"%")] Token op, PrecExpr right) { }
}

[Precedence(6)]
public sealed partial class Op6Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"&")] Token op, PrecExpr right) { }
}

[Precedence(7)]
public sealed partial class Op7Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\|")] Token op, PrecExpr right) { }
}

[Precedence(8)]
public sealed partial class Op8Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\^")] Token op, PrecExpr right) { }
}

[Precedence(9)]
public sealed partial class Op9Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"<")] Token op, PrecExpr right) { }
}

[Precedence(10)]
public sealed partial class Op10Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@">")] Token op, PrecExpr right) { }
}

[Precedence(11)]
public sealed partial class Op11Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"=")] Token op, PrecExpr right) { }
}

[Precedence(12)]
public sealed partial class Op12Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"~")] Token op, PrecExpr right) { }
}

[Precedence(13)]
public sealed partial class Op13Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"!")] Token op, PrecExpr right) { }
}

[Precedence(14)]
public sealed partial class Op14Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"@")] Token op, PrecExpr right) { }
}

[Precedence(15)]
public sealed partial class Op15Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"#")] Token op, PrecExpr right) { }
}

[Precedence(16)]
public sealed partial class Op16Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\$")] Token op, PrecExpr right) { }
}

[Precedence(17)]
public sealed partial class Op17Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"\?")] Token op, PrecExpr right) { }
}

[Precedence(18)]
public sealed partial class Op18Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@":")] Token op, PrecExpr right) { }
}

[Precedence(19)]
public sealed partial class Op19Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@";")] Token op, PrecExpr right) { }
}

[Precedence(20)]
public sealed partial class Op20Expr : PrecExpr
{
    [Rule]
    public static void Reduce(PrecExpr left, [Pattern(@"`")] Token op, PrecExpr right) { }
}

