using System.Collections.Generic;
using System.Text;
using AstFirst.Core.Lexing;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel からレクサ/パーサの C# コードを生成する。
/// 生成コードは Core (Dfa/Lexer/LalrTable 等) に依存する。
/// </summary>
public static class CodeEmitter
{
    /// <summary>レクサの C# コードを生成。DFA を static 配列に直列化し Lexer を駆動。</summary>
    public static string EmitLexer(GrammarModel model, Dfa dfa, IReadOnlyList<LexerRule> rules, string className, string ns)
    {
        var boundaries = dfa.Alphabet.Boundaries;
        int stateCount = dfa.States.Count;
        int classCount = dfa.Alphabet.ClassCount;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstFirst.Core.Lexing;");
        sb.AppendLine();
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("public static class " + className);
        sb.AppendLine("{");

        // Boundaries
        sb.Append("    public static readonly int[] Boundaries = new int[] { ");
        for (int i = 0; i < boundaries.Count; i++) { if (i > 0) sb.Append(", "); sb.Append(boundaries[i]); }
        sb.AppendLine(" };");

        // Transitions[state, class]
        sb.Append("    public static readonly int[,] Transitions = new int[");
        sb.Append(stateCount).Append(", ").Append(classCount).AppendLine("]");
        sb.AppendLine("    {");
        for (int s = 0; s < stateCount; s++)
        {
            sb.Append("        { ");
            var tr = dfa.States[s].Transitions;
            for (int c = 0; c < classCount; c++) { if (c > 0) sb.Append(", "); sb.Append(tr[c]); }
            sb.Append(" }");
            sb.AppendLine(s < stateCount - 1 ? "," : "");
        }
        sb.AppendLine("    };");

        // AcceptTokenIds[state]: 0 = 非受理
        sb.Append("    public static readonly int[] AcceptTokenIds = new int[] { ");
        for (int s = 0; s < stateCount; s++)
        {
            if (s > 0) sb.Append(", ");
            sb.Append(dfa.States[s].IsAccept ? dfa.States[s].AcceptTokenId : 0);
        }
        sb.AppendLine(" };");

        // Alphabet: アルファベット分割 (1回だけ構築してキャッシュ)。
        sb.AppendLine("    public static readonly AlphabetPartition Alphabet = AlphabetPartition.FromBoundaries(Boundaries);");

        // Rules: 字句規則 (1回だけ構築してキャッシュ)。
        sb.Append("    public static readonly LexerRule[] Rules = new LexerRule[] {");
        for (int i = 0; i < rules.Count; i++)
        {
            var r = rules[i];
            sb.AppendLine();
            sb.Append("        new LexerRule(\"").Append(Escape(r.Pattern)).Append("\", ")
              .Append(r.TokenId).Append(", ").Append(r.Priority).Append(", ").Append(r.IsHidden ? "true" : "false").Append("),");
        }
        sb.AppendLine();
        sb.AppendLine("    };");

        // Tokenize: static 配列 (Transitions/AcceptTokenIds) とキャッシュ済みの Alphabet/Rules を
        // 直接 Lexer.Tokenize に渡す。Dfa/DfaState オブジェクトの毎回の構築・コピーを回避する。
        sb.AppendLine("    /// <summary>Tokenizes the input into a list of tokens.</summary>");
        sb.AppendLine("    /// <remarks>入力をトークン列に分割します (DFA テーブルは static 配列を直接参照)。</remarks>");
        sb.AppendLine("    public static List<LexToken> Tokenize(string input)");
        sb.AppendLine("        => Lexer.Tokenize(Transitions, AcceptTokenIds, Alphabet, 0, Rules, input);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static (string ns, string type) SplitFullName(string fullName)
    {
        int i = fullName.LastIndexOf('.');
        return i < 0 ? ("", fullName) : (fullName.Substring(0, i), fullName.Substring(i + 1));
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
