using System.Collections.Generic;
using System.Text;
using AstFirst.Core.Lexing;
using AstFirst.Core.Parsing;

namespace AstFirst.Generator;

/// <summary>
/// LightGlr モード専用のパーサコード生成エミッタ。
/// <see cref="ParserEmitter"/> と同じテーブル直列化 (LALR(1) 表を static 配列に) を行いつつ、
/// Parse 本体は <c>AstFirst.Glr.LightGlrDriver</c> に委譲する (コンフリクトセルで並行 fork)。
/// reduce は <c>object?[] children</c> を受け取り COW (copy-on-write) でリストを構築 (GSS での共有安全)。
/// partial ノード生成は <see cref="ParserEmitter.EmitPartial"/> をそのまま流用 (OnReduce は reduce 時呼び出し)。
/// </summary>
internal static class GlrParserEmitter
{
    public static string EmitParser(GrammarModel model, Grammar grammar, LalrTable table, IReadOnlyList<LexerRule> rules, string ns)
    {
        int stateCount = table.StateCount;
        int symbolCount = table.SymbolCount;
        int prodCount = grammar.Productions.Count;
        var (typeName, lexerName, parserName) = Names(model);

        // 終端 Symbol.Id と LexerRule.TokenId を突き合わせ (ParserEmitter と同一)。
        var patternToTerminalId = new Dictionary<string, int>();
        foreach (var sym in grammar.Symbols)
        {
            if (!sym.IsTerminal) continue;
            if (sym.Name.StartsWith("token:"))
                patternToTerminalId[sym.Name.Substring("token:".Length)] = sym.Id;
        }

        var tokenDerivedTypes = new HashSet<string>();
        foreach (var td in model.TokenDefs)
            if (td.Key != "AstFirst.Token") tokenDerivedTypes.Add(td.Key);
        int maxTokenId = 0;
        foreach (var r in rules) if (r.TokenId > maxTokenId) maxTokenId = r.TokenId;
        var tokenIdToSym = new int[maxTokenId + 1];
        for (int i = 0; i < tokenIdToSym.Length; i++) tokenIdToSym[i] = -1;
        foreach (var r in rules)
            if (patternToTerminalId.TryGetValue(r.Pattern, out var sid))
                tokenIdToSym[r.TokenId] = sid;

        int eofSym = grammar.EndOfFile.Id;

        // コンフリクトセルの全候補を収集 (ParserEmitter と同一)。
        var altKeys = new List<int>();
        var altActs = new List<List<int>>();
        for (int s = 0; s < stateCount; s++)
            for (int c = 0; c < symbolCount; c++)
            {
                var alts = table.Alternatives(s, c);
                if (alts.Count < 2) continue;
                var list = new List<int>();
                for (int k = 1; k < alts.Count; k++) list.Add(EncodeAction(alts[k]));
                if (list.Count == 0) continue;
                altKeys.Add(s * symbolCount + c);
                altActs.Add(list);
            }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstFirst.Core.Lexing;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("public static class " + parserName);
        sb.AppendLine("{");
        if (model.HasSecondPass)
        {
            var walkerSuffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
            var (_, rootType) = CodeEmitter.SplitFullName(model.RootTypeFullName);
            var walkerName = rootType + walkerSuffix + "Walker";
            sb.AppendLine("    private static readonly " + walkerName + " __defaultWalker = new " + walkerName + "._Default();");
        }

        EmitMatrixByte(sb, "ActionKind", stateCount, symbolCount, s => c => ActionKindByte(table.Action(s, c)));
        EmitMatrixIntRaw(sb, "ActionValue", stateCount, symbolCount, s => c => table.Action(s, c).Value);
        EmitMatrixIntRaw(sb, "Goto", stateCount, symbolCount, s => c => table.Goto(s, c));

        sb.Append("    public static readonly int[] ProdLhs = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Lhs.Id); }
        sb.AppendLine(" };");
        sb.Append("    public static readonly int[] ProdLen = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Rhs.Length); }
        sb.AppendLine(" };");

        sb.Append("    public static readonly int[] TokenIdToSym = new int[] { ");
        for (int i = 0; i < tokenIdToSym.Length; i++) { if (i > 0) sb.Append(", "); sb.Append(tokenIdToSym[i]); }
        sb.AppendLine(" };");

        sb.AppendLine("    public const int EofSym = " + eofSym + ";");
        sb.AppendLine("    public const int StateCount = " + stateCount + ";");
        sb.AppendLine("    public const int SymbolCount = " + symbolCount + ";");

        sb.Append("    public static readonly string?[] SymNames = new string?[] { ");
        for (int si = 0; si < symbolCount; si++)
        {
            if (si > 0) sb.Append(", ");
            var escaped = grammar.Symbols[si].Name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.Append("\"").Append(escaped).Append("\"");
        }
        sb.AppendLine(" };");

        var dr = table.DefaultReduceTable;
        sb.Append("    public static readonly int[] DefaultReduce = new int[] { ");
        for (int s = 0; s < stateCount; s++) { if (s > 0) sb.Append(", "); sb.Append(s < dr.Count ? dr[s] : -1); }
        sb.AppendLine(" };");

        sb.Append("    public static readonly int[] AltKeys = new int[] { ");
        for (int i = 0; i < altKeys.Count; i++) { if (i > 0) sb.Append(", "); sb.Append(altKeys[i]); }
        sb.AppendLine(" };");
        sb.AppendLine("    public static readonly int[][] AltActs = new int[" + altActs.Count + "][]");
        sb.AppendLine("    {");
        for (int i = 0; i < altActs.Count; i++)
        {
            sb.Append("        new int[] { ");
            for (int j = 0; j < altActs[i].Count; j++) { if (j > 0) sb.Append(", "); sb.Append(altActs[i][j]); }
            sb.Append(" }");
            sb.AppendLine(i < altActs.Count - 1 ? "," : "");
        }
        sb.AppendLine("    };");

        EmitGlrParse(sb, lexerName, model);
        EmitGlrHelpers(sb, grammar, model, tokenDerivedTypes);

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitPartial(GrammarModel model, NodeModel node, string ns)
        => ParserEmitter.EmitPartial(model, node, ns);

    private static void EmitGlrParse(StringBuilder sb, string lexerName, GrammarModel model)
    {
        sb.AppendLine("    public static AstFirst.ParseResult Parse(string input) => Parse(input, null);");
        sb.AppendLine("    public static AstFirst.ParseResult Parse(string input, AstFirst.SemanticContext? context)");
        sb.AppendLine("    {");
        sb.AppendLine("        var ctx = (context as AstFirst.BasicSemanticContext) ?? new AstFirst.BasicSemanticContext();");
        sb.AppendLine("        var tokens = " + lexerName + ".Tokenize(input);");
        sb.AppendLine("        var __tables = new AstFirst.Glr.GlrTables(ActionKind, ActionValue, Goto, ProdLhs, ProdLen, DefaultReduce, TokenIdToSym, AltKeys, AltActs, StateCount, SymbolCount, EofSym, 0, SymNames);");
        sb.AppendLine("        var __r = AstFirst.Glr.LightGlrDriver.Run(__tables, tokens, ctx, __ReduceNode, __ToToken);");
        sb.AppendLine("        object? result = __r.Candidates.Count > 0 ? __r.Candidates[0] : null;");
        if (model.HasSecondPass)
            sb.AppendLine("        if (result is AstFirst.AstNode __root) __defaultWalker.Walk(__root, ctx);");
        sb.AppendLine("        return new AstFirst.ParseResult(result, __r.Errors, ctx.Diagnostics.Items, __r.Candidates.Count > 1 ? __r.Candidates : null);");
        sb.AppendLine("    }");
    }

    private static void EmitGlrHelpers(StringBuilder sb, Grammar grammar, GrammarModel model, HashSet<string> tokenDerivedTypes)
    {
        // __ReduceNode: 規則 prodId で reduce。children[i] (右辺 i 番目) を参照 → partial コンストラクタ new。
        // ListReduceActionModel の再帰ケースは COW (copy-on-write): 共有スタックで破壊しないよう新リストを構築。
        sb.AppendLine("    private static object? __ReduceNode(int val, object?[] children, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (val)");
        sb.AppendLine("        {");
        foreach (var prod in grammar.Productions)
        {
            switch (prod.Tag)
            {
                case ReduceActionModel action:
                {
                    sb.Append("            case ").Append(prod.Id).Append(": { return new ").Append(action.AstTypeName).Append("(\"").Append(action.RuleName).Append("\"");
                    for (int j = 0; j < action.Parameters.Count; j++)
                    {
                        sb.Append(", ");
                        var p = action.Parameters[j];
                        if (p.IsContext) sb.Append("(").Append(p.CastTypeName).Append(")ctx");
                        else if (tokenDerivedTypes.Contains(p.CastTypeName)) sb.Append("new ").Append(p.CastTypeName).Append("(((AstFirst.Token)children[").Append(p.ChildIndex).Append("]!).Text)");
                        else sb.Append("(").Append(p.CastTypeName).Append(")children[").Append(p.ChildIndex).Append("]!");
                    }
                    sb.AppendLine("); }");
                    break;
                }
                case ListReduceActionModel listAction:
                {
                    string elemType = listAction.ElementType;
                    string listType = "System.Collections.Generic.List<" + elemType + ">";
                    sb.Append("            case ").Append(prod.Id).Append(": { ");
                    if (listAction.IsRecursive)
                    {
                        // List_T → List_T item: COW。既存リストをコピーして末尾に item を add (共有スタックで安全)。
                        sb.Append("var __src = (").Append(listType).Append(")children[0]!; ");
                        sb.Append("var __list = new ").Append(listType).Append("(__src.Count + 1); ");
                        sb.Append("foreach (var __x in __src) __list.Add(__x); ");
                        sb.Append("__list.Add((").Append(elemType).Append(")children[1]!); ");
                    }
                    else if (listAction.IsEmpty)
                    {
                        sb.Append("var __list = new ").Append(listType).Append("(0); ");
                    }
                    else
                    {
                        sb.Append("var __list = new ").Append(listType).Append("(4); ");
                        sb.Append("__list.Add((").Append(elemType).Append(")children[0]!); ");
                    }
                    sb.AppendLine("return __list; }");
                    break;
                }
                case PassThroughActionModel:
                {
                    sb.Append("            case ").Append(prod.Id).Append(": { return children[0]!; }").AppendLine();
                    break;
                }
            }
        }
        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("    private static AstFirst.Token __ToToken(AstFirst.Core.Lexing.LexToken t)");
        sb.AppendLine("        => new AstFirst.BasicToken(t.Span, new AstFirst.SourceSpan(new AstFirst.Position(t.Start, t.StartLine, t.StartColumn), new AstFirst.Position(t.End, t.EndLine, t.EndColumn)));");
    }

    private static int EncodeAction(LrAction a)
    {
        int k = a.Kind switch { LrActionKind.Shift => 1, LrActionKind.Reduce => 2, LrActionKind.Accept => 3, _ => 0 };
        return k * 1000000 + (a.Value < 0 ? 0 : a.Value);
    }

    private static byte ActionKindByte(LrAction a) => a.Kind switch
    {
        LrActionKind.Shift => 1,
        LrActionKind.Reduce => 2,
        LrActionKind.Accept => 3,
        _ => 0
    };

    private static (string type, string lexer, string parser) Names(GrammarModel model)
    {
        var (ns, type) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        var suffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
        return (type + suffix, type + suffix + "Lexer", type + suffix + "Parser");
    }

    private static void EmitMatrixByte(StringBuilder sb, string name, int rows, int cols,
        System.Func<int, System.Func<int, byte>> cell)
    {
        sb.Append("    public static readonly byte[] ").Append(name).Append(" = new byte[").Append(rows * cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }

    private static void EmitMatrixIntRaw(StringBuilder sb, string name, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
    {
        sb.Append("    public static readonly int[] ").Append(name).Append(" = new int[").Append(rows * cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }
}
