using System.Linq;
using System.Text;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel から型安全 Listener (ANTLR 風) を生成する。
/// 各具象ノードの Enter/Exit メソッドと、Enter → 子再帰 → Exit を駆動する Walk を持つ抽象クラス。
/// ユーザーは継承して EnterXxx/ExitXxx を override し、Walk(ルート) を呼んで意味解析等を行う。
/// </summary>
public static class ListenerEmitter
{
    public static string EmitListener(GrammarModel model, string ns)
    {
        var (_, rootType) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        var suffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
        var listenerName = rootType + suffix + "Listener";

        var concrete = model.Nodes.Where(n => !n.IsAbstract).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using AstFirst;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("/// <summary>AST Listener。Walk で Enter→子再帰→Exit を駆動。EnterXxx/ExitXxx を override して使う。</summary>");
        sb.AppendLine("public abstract class " + listenerName);
        sb.AppendLine("{");

        // Walk: EnterEach → 子を再帰 Walk → ExitEach
        sb.AppendLine("    /// <summary>Walks a node: EnterEach, then recurses children, then ExitEach.</summary>");
        sb.AppendLine("    /// <remarks>ノードを訪問します: EnterEach → 子を再帰 Walk → ExitEach。</remarks>");
        sb.AppendLine("    public virtual void Walk(AstFirst.AstNode node)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (node is null) return;");
        sb.AppendLine("        EnterEach(node);");
        if (concrete.Count > 0)
        {
            sb.AppendLine("        switch (node)");
            sb.AppendLine("        {");
            foreach (var n in concrete)
            {
                sb.Append("            case ").Append(n.FullName).AppendLine(" n:");
                sb.AppendLine("            {");
                foreach (var c in n.Children)
                {
                    if (c.IsNullable)
                        sb.AppendLine("                if (n." + c.PropertyName + " is not null) Walk(n." + c.PropertyName + ");");
                    else
                        sb.AppendLine("                Walk(n." + c.PropertyName + ");");
                }
                sb.AppendLine("                break;");
                sb.AppendLine("            }");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine("        ExitEach(node);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EnterEach
        sb.AppendLine("    /// <summary>Dispatches to the EnterXxx override matching the node's type.</summary>");
        sb.AppendLine("    /// <remarks>ノードの型に応じた EnterXxx を呼び出します。</remarks>");
        sb.AppendLine("    public virtual void EnterEach(AstFirst.AstNode node)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (node)");
        sb.AppendLine("        {");
        foreach (var n in concrete)
            sb.Append("            case ").Append(n.FullName).Append(" n: Enter").Append(SimpleName(n.FullName)).AppendLine("(n); break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ExitEach
        sb.AppendLine("    /// <summary>Dispatches to the ExitXxx override matching the node's type.</summary>");
        sb.AppendLine("    /// <remarks>ノードの型に応じた ExitXxx を呼び出します。</remarks>");
        sb.AppendLine("    public virtual void ExitEach(AstFirst.AstNode node)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (node)");
        sb.AppendLine("        {");
        foreach (var n in concrete)
            sb.Append("            case ").Append(n.FullName).Append(" n: Exit").Append(SimpleName(n.FullName)).AppendLine("(n); break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // EnterXxx / ExitXxx (具象ノード毎)
        foreach (var n in concrete)
        {
            var sn = SimpleName(n.FullName);
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Called when entering a " + n.FullName + " node. Override to handle it.</summary>");
            sb.AppendLine("    /// <remarks>" + sn + " ノードに入る時に呼ばれます。オーバーライドして処理します。</remarks>");
            sb.AppendLine("    public virtual void Enter" + sn + "(" + n.FullName + " node) { }");
            sb.AppendLine("    /// <summary>Called when leaving a " + n.FullName + " node. Override to handle it.</summary>");
            sb.AppendLine("    /// <remarks>" + sn + " ノードを出る時に呼ばれます。オーバーライドして処理します。</remarks>");
            sb.AppendLine("    public virtual void Exit" + sn + "(" + n.FullName + " node) { }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SimpleName(string fullName)
    {
        var idx = fullName.LastIndexOf('.');
        return idx < 0 ? fullName : fullName.Substring(idx + 1);
    }
}
