using System.Collections.Generic;
using System.Text;
using AstFirst.Core.Parsing;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel からパーサの C# コードを生成する。
/// LalrTable (ACTION/GOTO) と Productions を static 配列に直列化し、
/// shift/reduce/accept を駆動する。Lexer の TokenId と文法の終端 Id は
/// Pattern で結んでマップする。reduce 時の AST 構築 (コンストラクタ呼び出し) は
/// フェーズ (4) で差し替えるため、ここではスタブ値を積む。
/// </summary>
public static class ParserEmitter
{
    public static string EmitParser(GrammarModel model, string ns)
    {
        var (grammar, table) = ModelToTable.BuildWithGrammar(model);
        var dfa = ModelToDfa.Build(model, out var rules);

        int stateCount = table.StateCount;
        int symbolCount = table.SymbolCount;
        int prodCount = grammar.Productions.Count;
        var (typeName, lexerName, parserName) = Names(model);

        // 終端 Symbol.Id (Pattern 列挙) と LexerRule.TokenId (Pattern 列挙) を突き合わせ。
        var patternToTerminalId = new Dictionary<string, int>();
        foreach (var sym in grammar.Symbols)
        {
            if (!sym.IsTerminal) continue;
            if (sym.Name.StartsWith("token:"))
                patternToTerminalId[sym.Name.Substring("token:".Length)] = sym.Id;
        }
        // tokenId -> terminal Symbol.Id
        int maxTokenId = 0;
        foreach (var r in rules) if (r.TokenId > maxTokenId) maxTokenId = r.TokenId;
        var tokenIdToSym = new int[maxTokenId + 1]; // 1..maxTokenId を使用
        for (int i = 0; i < tokenIdToSym.Length; i++) tokenIdToSym[i] = -1;
        foreach (var r in rules)
        {
            if (patternToTerminalId.TryGetValue(r.Pattern, out var sid))
                tokenIdToSym[r.TokenId] = sid;
        }

        int eofSym = grammar.EndOfFile.Id;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstFirst.Core.Lexing;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("public static class " + parserName);
        sb.AppendLine("{");

        // ActionKind / ActionValue
        EmitMatrixByte(sb, "ActionKind", table, stateCount, symbolCount, s => c => ActionKindByte(table.Action(s, c)));
        EmitMatrixInt(sb, "ActionValue", table, stateCount, symbolCount, s => c => table.Action(s, c).Value);
        EmitMatrixIntRaw(sb, "Goto", stateCount, symbolCount, s => c => table.Goto(s, c));

        // Productions: LHS と右辺長さ
        sb.Append("    public static readonly int[] ProdLhs = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Lhs.Id); }
        sb.AppendLine(" };");
        sb.Append("    public static readonly int[] ProdLen = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Rhs.Length); }
        sb.AppendLine(" };");

        // TokenIdToSym
        sb.Append("    public static readonly int[] TokenIdToSym = new int[] { ");
        for (int i = 0; i < tokenIdToSym.Length; i++) { if (i > 0) sb.Append(", "); sb.Append(tokenIdToSym[i]); }
        sb.AppendLine(" };");

        sb.AppendLine("    public const int EofSym = " + eofSym + ";");
        sb.AppendLine("    public const int StateCount = " + stateCount + ";");
        sb.AppendLine("    public const int SymbolCount = " + symbolCount + ";");

        // [Context] を使う規則があれば BasicSemanticContext を用意。
        bool needsContext = false;
        for (int pi = 0; pi < grammar.Productions.Count; pi++)
            if (grammar.Productions[pi].Tag is ReduceActionModel am && am.Parameters.Any(p => p.IsContext))
                { needsContext = true; break; }

        // Parse
        sb.AppendLine("    public static object? Parse(string input)");
        sb.AppendLine("    {");
        if (needsContext)
            sb.AppendLine("        var ctx = new AstFirst.BasicSemanticContext();");
        sb.AppendLine("        var tokens = " + lexerName + ".Tokenize(input);");
        sb.AppendLine("        var states = new Stack<int>();");
        sb.AppendLine("        var values = new Stack<object?>();");
        sb.AppendLine("        states.Push(0);");
        sb.AppendLine("        int i = 0;");
        sb.AppendLine("        while (true)");
        sb.AppendLine("        {");
        sb.AppendLine("            int state = states.Peek();");
        sb.AppendLine("            int sym = (i < tokens.Count) ? TokenIdToSym[tokens[i].TokenId] : EofSym;");
        sb.AppendLine("            if (sym < 0) throw new System.Exception(\"未知のトークンです。\");");
        sb.AppendLine("            byte kind = ActionKind[state, sym];");
        sb.AppendLine("            int val = ActionValue[state, sym];");
        sb.AppendLine("            if (kind == 1) // Shift");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Push(sym == EofSym ? null : (object)ToToken(tokens[i]));");
        sb.AppendLine("                states.Push(val);");
        sb.AppendLine("                i++;");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (kind == 2) // Reduce");
        sb.AppendLine("            {");
        sb.AppendLine("                object? node;");
        sb.AppendLine("                switch (val)");
        sb.AppendLine("                {");
        for (int pi = 0; pi < grammar.Productions.Count; pi++)
        {
            var prod = grammar.Productions[pi];
            if (prod.Tag is not ReduceActionModel action) continue;
            sb.Append("                    case ").Append(prod.Id).Append(": { var c = PopN(values, ").Append(prod.Rhs.Length).Append("); PopN(states, ").Append(prod.Rhs.Length).Append("); node = new ").Append(action.AstTypeName).Append("(");
            for (int i = 0; i < action.Parameters.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var p = action.Parameters[i];
                if (p.IsContext) sb.Append("ctx");
                else sb.Append("(").Append(p.CastTypeName).Append(")c[").Append(p.ChildIndex).Append("]");
            }
            sb.AppendLine("); break; }");
        }
        sb.AppendLine("                    default: { PopN(values, ProdLen[val]); PopN(states, ProdLen[val]); node = null; break; }");
        sb.AppendLine("                }");
        sb.AppendLine("                values.Push(node);");
        sb.AppendLine("                states.Push(Goto[states.Peek(), ProdLhs[val]]);");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (kind == 3) // Accept");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Pop(); // $ を捨てる");
        sb.AppendLine("                return values.Peek();");
        sb.AppendLine("            }");
        sb.AppendLine("            else throw new System.Exception(\"構文エラー: 状態 \" + state + \" で予期しないトークンです。\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("    private static T[] PopN<T>(Stack<T> s, int n)");
        sb.AppendLine("    {");
        sb.AppendLine("        var a = new T[n];");
        sb.AppendLine("        for (int i = 0; i < n; i++) a[n - 1 - i] = s.Pop();");
        sb.AppendLine("        return a;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static AstFirst.Token ToToken(AstFirst.Core.Lexing.LexToken t)");
        sb.AppendLine("        => new AstFirst.BasicToken(t.Text, new AstFirst.SourceSpan(new AstFirst.Position(t.Start, 0, 0), new AstFirst.Position(t.End, 0, 0)));");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static byte ActionKindByte(LrAction a) => a.Kind switch
    {
        LrActionKind.Shift => 1,
        LrActionKind.Reduce => 2,
        LrActionKind.Accept => 3,
        _ => 0
    };

    private static (string type, string lexer, string parser) Names(GrammarModel model)
    {
        var (ns, type) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        return (type, type + "Lexer", type + "Parser");
    }

    private static void EmitMatrixByte(StringBuilder sb, string name, LalrTable _, int rows, int cols,
        System.Func<int, System.Func<int, byte>> cell)
    {
        sb.Append("    public static readonly byte[,] ").Append(name).Append(" = new byte[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }

    private static void EmitMatrixInt(StringBuilder sb, string name, LalrTable _, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
        => EmitMatrixIntRaw(sb, name, rows, cols, s => cell(s));

    private static void EmitMatrixIntRaw(StringBuilder sb, string name, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
    {
        sb.Append("    public static readonly int[,] ").Append(name).Append(" = new int[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }
}
