using System.Collections.Generic;
using System.Text;
using AstFirst.Core.Lexing;
using AstFirst.Core.Parsing;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel からパーサの C# コードを生成する。
/// LalrTable (ACTION/GOTO/Alternatives) と Productions を static 配列に直列化し、
/// shift/reduce/accept を駆動する。reduce は「仮想 reduce」: PeekN (Pop せず参照) で
/// partial コンストラクタ new → OnReduce(ctx) → Accept/Reject を判定。Reject なら
/// Alternatives の次候補へフォールバック。Parse 後に 2パス目 (OnSecondPassEnter/Exit) を自動呼出。
/// </summary>
public static class ParserEmitter
{
    public static string EmitParser(GrammarModel model, Grammar grammar, LalrTable table, IReadOnlyList<LexerRule> rules, string ns)
    {
        int stateCount = table.StateCount;
        int symbolCount = table.SymbolCount;
        int prodCount = grammar.Productions.Count;
        var (typeName, lexerName, parserName) = Names(model);

        // 終端 Symbol.Id と LexerRule.TokenId を突き合わせ。
        var patternToTerminalId = new Dictionary<string, int>();
        foreach (var sym in grammar.Symbols)
        {
            if (!sym.IsTerminal) continue;
            if (sym.Name.StartsWith("token:"))
                patternToTerminalId[sym.Name.Substring("token:".Length)] = sym.Id;
        }

        // Token 派生型。reduce 時、BasicToken.Text から派生型を再生成。
        var tokenDerivedTypes = new HashSet<string>();
        foreach (var td in model.TokenDefs)
            if (td.Key != "AstFirst.Token") tokenDerivedTypes.Add(td.Key);
        int maxTokenId = 0;
        foreach (var r in rules) if (r.TokenId > maxTokenId) maxTokenId = r.TokenId;
        var tokenIdToSym = new int[maxTokenId + 1];
        for (int i = 0; i < tokenIdToSym.Length; i++) tokenIdToSym[i] = -1;
        foreach (var r in rules)
            if (patternToTerminalId.TryGetValue(r.Pattern, out var sid))
                tokenIdToSym[r.TokenId] = sid;

        int eofSym = grammar.EndOfFile.Id;

        // コンフリクトセルのフォールバック候補を収集 (候補2以上のセルのみ)。
        var altKeys = new List<int>();
        var altActs = new List<List<int>>();
        for (int s = 0; s < stateCount; s++)
            for (int c = 0; c < symbolCount; c++)
            {
                var alts = table.Alternatives(s, c);
                if (alts.Count < 2) continue;
                // デフォルト (先頭) は Action(s,c) と同じはず。敗者候補 (2番目以降) を記録。
                var list = new List<int>();
                for (int k = 1; k < alts.Count; k++) list.Add(EncodeAction(alts[k]));
                if (list.Count == 0) continue;
                altKeys.Add(s * symbolCount + c);
                altActs.Add(list);
            }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstFirst.Core.Lexing;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("public static class " + parserName);
        sb.AppendLine("{");

        EmitMatrixByte(sb, "ActionKind", table, stateCount, symbolCount, s => c => ActionKindByte(table.Action(s, c)));
        EmitMatrixIntRaw(sb, "ActionValue", stateCount, symbolCount, s => c => table.Action(s, c).Value);
        EmitMatrixIntRaw(sb, "Goto", stateCount, symbolCount, s => c => table.Goto(s, c));

        sb.Append("    public static readonly int[] ProdLhs = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Lhs.Id); }
        sb.AppendLine(" };");
        sb.Append("    public static readonly int[] ProdLen = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Rhs.Length); }
        sb.AppendLine(" };");

        sb.Append("    public static readonly int[] TokenIdToSym = new int[] { ");
        for (int i = 0; i < tokenIdToSym.Length; i++) { if (i > 0) sb.Append(", "); sb.Append(tokenIdToSym[i]); }
        sb.AppendLine(" };");

        sb.AppendLine("    public const int EofSym = " + eofSym + ";");
        sb.AppendLine("    public const int StateCount = " + stateCount + ";");
        sb.AppendLine("    public const int SymbolCount = " + symbolCount + ";");

        sb.Append("    public static readonly string?[] SymNames = new string?[] { ");
        for (int si = 0; si < symbolCount; si++)
        {
            if (si > 0) sb.Append(", ");
            var escaped = grammar.Symbols[si].Name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.Append("\"").Append(escaped).Append("\"");
        }
        sb.AppendLine(" };");

        var dr = table.DefaultReduceTable;
        sb.Append("    public static readonly int[] DefaultReduce = new int[] { ");
        for (int s = 0; s < stateCount; s++) { if (s > 0) sb.Append(", "); sb.Append(s < dr.Count ? dr[s] : -1); }
        sb.AppendLine(" };");

        // フォールバック候補 (コンフリクトセル)
        sb.Append("    private static readonly int[] AltKeys = new int[] { ");
        for (int i = 0; i < altKeys.Count; i++) { if (i > 0) sb.Append(", "); sb.Append(altKeys[i]); }
        sb.AppendLine(" };");
        sb.AppendLine("    private static readonly int[][] AltActs = new int[" + altActs.Count + "][]");
        sb.AppendLine("    {");
        for (int i = 0; i < altActs.Count; i++)
        {
            sb.Append("        new int[] { ");
            for (int j = 0; j < altActs[i].Count; j++) { if (j > 0) sb.Append(", "); sb.Append(altActs[i][j]); }
            sb.Append(" }");
            sb.AppendLine(i < altActs.Count - 1 ? "," : "");
        }
        sb.AppendLine("    };");

        EmitParse(sb, lexerName);
        EmitHelpers(sb, grammar, model, tokenDerivedTypes);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitParse(StringBuilder sb, string lexerName)
    {
        sb.AppendLine("    public static AstFirst.ParseResult Parse(string input) => Parse(input, null);");
        sb.AppendLine("    public static AstFirst.ParseResult Parse(string input, AstFirst.SemanticContext? context)");
        sb.AppendLine("    {");
        sb.AppendLine("        var ctx = context ?? new AstFirst.BasicSemanticContext();");
        sb.AppendLine("        var tokens = " + lexerName + ".Tokenize(input);");
        sb.AppendLine("        var states = new Stack<int>();");
        sb.AppendLine("        var values = new Stack<object?>();");
        sb.AppendLine("        var errors = new System.Collections.Generic.List<AstFirst.ParseError>();");
        sb.AppendLine("        object? result = null;");
        sb.AppendLine("        states.Push(0);");
        sb.AppendLine("        int i = 0;");
        sb.AppendLine("        int lastErrorPos = -10;");
        sb.AppendLine("        while (true)");
        sb.AppendLine("        {");
        sb.AppendLine("            int state = states.Peek();");
        sb.AppendLine("            int sym = (i < tokens.Count) ? TokenIdToSym[tokens[i].TokenId] : EofSym;");
        sb.AppendLine("            if (sym < 0) { errors.Add(new AstFirst.ParseError(\"未知のトークンです\", tokens[i].Start)); i++; continue; }");
        sb.AppendLine("            byte kind = ActionKind[state, sym];");
        sb.AppendLine("            int val = ActionValue[state, sym];");
        sb.AppendLine("            int dr = DefaultReduce[state];");
        sb.AppendLine("            // デフォルトアクション決定 (テーブル圧縮のデフォルト reduce を展開)");
        sb.AppendLine("            byte dk = kind; int dv = val;");
        sb.AppendLine("            if (kind == 0 && dr >= 0) { dk = 2; dv = dr; }");
        sb.AppendLine("");
        sb.AppendLine("            if (dk == 1) // Shift");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Push(sym == EofSym ? null : (object)ToToken(tokens[i]));");
        sb.AppendLine("                states.Push(dv);");
        sb.AppendLine("                i++;");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (dk == 2) // Reduce (仮想 reduce)");
        sb.AppendLine("            {");
        sb.AppendLine("                var node = ReduceNode(dv, values, ctx);");
        sb.AppendLine("                if (node is not null && !((AstFirst.AstNode)node).IsAccepted)");
        sb.AppendLine("                {");
        sb.AppendLine("                    // Reject: フォールバック候補を試す");
        sb.AppendLine("                    if (!TryFallback(state, sym, values, states, ctx, tokens, ref i)) goto panic;");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    int len = ProdLen[dv];");
        sb.AppendLine("                    for (int k = 0; k < len; k++) { values.Pop(); states.Pop(); }");
        sb.AppendLine("                    values.Push(node);");
        sb.AppendLine("                    states.Push(Goto[states.Peek(), ProdLhs[dv]]);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (dk == 3) // Accept");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Pop(); // $ を捨てる");
        sb.AppendLine("                result = values.Peek();");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
        sb.AppendLine("            else { goto panic; }");
        sb.AppendLine("            continue;");
        sb.AppendLine("        panic:");
        sb.AppendLine("            {");
        sb.AppendLine("                int pos = i < tokens.Count ? tokens[i].Start : (tokens.Count > 0 ? tokens[tokens.Count - 1].End : 0);");
        sb.AppendLine("                if (i - lastErrorPos >= 3)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var exp = new System.Text.StringBuilder();");
        sb.AppendLine("                    for (int e = 0; e < SymbolCount; e++)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        if (ActionKind[state, e] == 0) continue;");
        sb.AppendLine("                        if (exp.Length > 0) exp.Append(\", \");");
        sb.AppendLine("                        exp.Append(e == EofSym ? \"EOF\" : e < SymNames.Length ? SymNames[e] : \"#\" + e);");
        sb.AppendLine("                    }");
        sb.AppendLine("                    errors.Add(new AstFirst.ParseError(\"予期しないトークン\" + (exp.Length > 0 ? \" (期待: \" + exp + \")\" : \"\"), pos));");
        sb.AppendLine("                    lastErrorPos = i;");
        sb.AppendLine("                }");
        sb.AppendLine("                bool recovered = false;");
        sb.AppendLine("                while (states.Count > 1 && i < tokens.Count)");
        sb.AppendLine("                {");
        sb.AppendLine("                    states.Pop(); values.Pop();");
        sb.AppendLine("                    int topState = states.Peek();");
        sb.AppendLine("                    int curSym = TokenIdToSym[tokens[i].TokenId];");
        sb.AppendLine("                    if (curSym >= 0 && ActionKind[topState, curSym] != 0) { recovered = true; break; }");
        sb.AppendLine("                }");
        sb.AppendLine("                if (!recovered)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (states.Count <= 1) { while (states.Count > 0) states.Pop(); while (values.Count > 0) values.Pop(); states.Push(0); }");
        sb.AppendLine("                    if (i < tokens.Count) i++; else break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        // 2パス目: AST 全体をトップダウンで OnSecondPassEnter/Exit");
        sb.AppendLine("        if (result is AstFirst.AstNode root) WalkSecondPass(root, ctx);");
        sb.AppendLine("        return new AstFirst.ParseResult(result, errors, ctx.Diagnostics.Items);");
        sb.AppendLine("    }");
    }

    private static void EmitHelpers(StringBuilder sb, Grammar grammar, GrammarModel model, HashSet<string> tokenDerivedTypes)
    {
        // TryFallback: Reject された reduce の代わりにコンフリクト候補を試す。
        sb.AppendLine("    private static bool TryFallback(int state, int sym, Stack<object?> values, Stack<int> states, AstFirst.SemanticContext ctx, System.Collections.Generic.List<AstFirst.Core.Lexing.LexToken> tokens, ref int i)");
        sb.AppendLine("    {");
        sb.AppendLine("        int key = state * SymbolCount + sym;");
        sb.AppendLine("        for (int a = 0; a < AltKeys.Length; a++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (AltKeys[a] != key) continue;");
        sb.AppendLine("            foreach (var e in AltActs[a])");
        sb.AppendLine("            {");
        sb.AppendLine("                int k = e / 1000000; int v = e % 1000000;");
        sb.AppendLine("                if (k == 1) // Shift 候補");
        sb.AppendLine("                {");
        sb.AppendLine("                    values.Push(sym == EofSym ? null : (object)ToToken(tokens[i]));");
        sb.AppendLine("                    states.Push(v);");
        sb.AppendLine("                    i++;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                }");
        sb.AppendLine("                if (k == 2) // Reduce 候補");
        sb.AppendLine("                {");
        sb.AppendLine("                    var node = ReduceNode(v, values, ctx);");
        sb.AppendLine("                    if (node is not null && !((AstFirst.AstNode)node).IsAccepted) continue; // さらに Reject → 次");
        sb.AppendLine("                    int len = ProdLen[v];");
        sb.AppendLine("                    for (int x = 0; x < len; x++) { values.Pop(); states.Pop(); }");
        sb.AppendLine("                    values.Push(node);");
        sb.AppendLine("                    states.Push(Goto[states.Peek(), ProdLhs[v]]);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");

        // PeekN: Pop せずスタックトップ n 個を参照 (仮想 reduce 用)。
        sb.AppendLine("    private static object?[] PeekN(Stack<object?> s, int n)");
        sb.AppendLine("    {");
        sb.AppendLine("        var a = new object?[n];");
        sb.AppendLine("        int idx = n - 1;");
        sb.AppendLine("        foreach (var v in s) { if (idx < 0) break; a[idx--] = v; }");
        sb.AppendLine("        return a;");
        sb.AppendLine("    }");

        // ReduceNode: 規則 prodId で仮想 reduce。PeekN で子を参照 → partial コンストラクタ new → OnReduce(ctx)。
        sb.AppendLine("    private static object? ReduceNode(int val, Stack<object?> values, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (val)");
        sb.AppendLine("        {");
        foreach (var prod in grammar.Productions)
        {
            if (prod.Tag is not ReduceActionModel action) continue;
            sb.Append("            case ").Append(prod.Id).Append(": { var c = PeekN(values, ").Append(prod.Rhs.Length).Append("); return new ").Append(action.AstTypeName).Append("(");
            for (int j = 0; j < action.Parameters.Count; j++)
            {
                if (j > 0) sb.Append(", ");
                var p = action.Parameters[j];
                if (p.IsContext) sb.Append("(").Append(p.CastTypeName).Append(")ctx");
                else if (tokenDerivedTypes.Contains(p.CastTypeName)) sb.Append("new ").Append(p.CastTypeName).Append("(((AstFirst.Token)c[").Append(p.ChildIndex).Append("]!).Text)");
                else sb.Append("(").Append(p.CastTypeName).Append(")c[").Append(p.ChildIndex).Append("]!");
            }
            sb.AppendLine("); }");
        }
        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // WalkSecondPass: AST をトップダウンで OnSecondPassEnter/Exit 呼出。
        sb.AppendLine("    private static void WalkSecondPass(AstFirst.AstNode node, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (node is null) return;");
        sb.AppendLine("        switch (node)");
        sb.AppendLine("        {");
        foreach (var n in model.Nodes)
        {
            if (n.IsAbstract) continue;
            sb.AppendLine("            case " + n.FullName + " __n:");
            sb.AppendLine("            {");
            sb.AppendLine("                __n.OnSecondPassEnter(ctx);");
            foreach (var c in n.Children)
            {
                if (c.IsNullable) sb.AppendLine("                if (__n." + c.PropertyName + " is not null) WalkSecondPass(__n." + c.PropertyName + ", ctx);");
                else sb.AppendLine("                WalkSecondPass(__n." + c.PropertyName + ", ctx);");
            }
            sb.AppendLine("                __n.OnSecondPassExit(ctx);");
            sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("    private static AstFirst.Token ToToken(AstFirst.Core.Lexing.LexToken t)");
        sb.AppendLine("        => new AstFirst.BasicToken(t.Span, new AstFirst.SourceSpan(new AstFirst.Position(t.Start, t.StartLine, t.StartColumn), new AstFirst.Position(t.End, t.EndLine, t.EndColumn)));");
    }

    /// <summary>各具象ノードの partial コード (子/終端プロパティ + OnReduce/OnSecondPass 宣言 + partial コンストラクタ) を生成。</summary>
    public static string EmitPartial(GrammarModel model, NodeModel node, string ns)
    {
        var (nodeNs, simple) = CodeEmitter.SplitFullName(node.FullName);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (nodeNs.Length > 0) { sb.AppendLine("namespace " + nodeNs + ";"); sb.AppendLine(); }

        string? ctxType = CtxTypeOf(node);
        string? ctxArg = CtxArgOf(node);
        string ctxParam = ctxType is not null ? "(" + ctxType + " " + (ctxArg ?? "ctx") + ")" : "()";
        string ctxCall = ctxType is not null ? (ctxArg ?? "ctx") : "";
        var rule = node.Rules.Count > 0 ? node.Rules[0] : null;

        sb.AppendLine("public partial class " + simple);
        sb.AppendLine("{");
        // 子 (AstNode 派生) + 終端 (Token) プロパティ: [Rule] 引数の ctx 以外 (PascalCase)
        if (rule is not null)
            foreach (var p in rule.Parameters)
                if (!p.IsContext && p.Name is not null)
                    sb.AppendLine("    public " + p.TypeFullName + " " + CodeEmitter.Pascalize(p.Name) + " { get; private set; } = default!;");
        sb.AppendLine("    partial void OnReduce" + ctxParam + ";");
        // OnSecondPassEnter/Exit は AstNode の public virtual (override して使用)。ここでは宣言しない。

        // partial コンストラクタ: [Rule] 引数を受け取り、子/終端をプロパティへセット → OnReduce。
        if (rule is not null)
        {
            sb.Append("    internal " + simple + "(");
            for (int j = 0; j < rule.Parameters.Count; j++)
            {
                if (j > 0) sb.Append(", ");
                sb.Append(rule.Parameters[j].TypeFullName).Append(" ").Append(rule.Parameters[j].Name ?? ("p" + j));
            }
            sb.AppendLine(")");
            sb.AppendLine("    {");
            foreach (var p in rule.Parameters)
                if (!p.IsContext && p.Name is not null)
                    sb.AppendLine("        this." + CodeEmitter.Pascalize(p.Name) + " = " + p.Name + ";");
            sb.AppendLine("        OnReduce(" + ctxCall + ");");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>ノードの [Rule] の最後の SemanticContext 派生引数の型。なければ null (ctx なし)。</summary>
    private static string? CtxTypeOf(NodeModel n)
    {
        if (n.Rules.Count == 0) return null;
        var ps = n.Rules[0].Parameters;
        for (int j = ps.Count - 1; j >= 0; j--)
            if (ps[j].IsContext) return ps[j].TypeFullName;
        return null;
    }

    /// <summary>ノードの ctx 引数の名前。なければ null。</summary>
    private static string? CtxArgOf(NodeModel n)
    {
        if (n.Rules.Count == 0) return null;
        var ps = n.Rules[0].Parameters;
        for (int j = ps.Count - 1; j >= 0; j--)
            if (ps[j].IsContext) return ps[j].Name ?? "ctx";
        return null;
    }

    private static int EncodeAction(LrAction a)
    {
        int k = a.Kind switch { LrActionKind.Shift => 1, LrActionKind.Reduce => 2, LrActionKind.Accept => 3, _ => 0 };
        return k * 1000000 + (a.Value < 0 ? 0 : a.Value);
    }

    private static byte ActionKindByte(LrAction a) => a.Kind switch
    {
        LrActionKind.Shift => 1,
        LrActionKind.Reduce => 2,
        LrActionKind.Accept => 3,
        _ => 0
    };

    private static (string type, string lexer, string parser) Names(GrammarModel model)
    {
        var (ns, type) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        var suffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
        return (type + suffix, type + suffix + "Lexer", type + suffix + "Parser");
    }

    private static void EmitMatrixByte(StringBuilder sb, string name, LalrTable _, int rows, int cols,
        System.Func<int, System.Func<int, byte>> cell)
    {
        sb.Append("    public static readonly byte[,] ").Append(name).Append(" = new byte[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }

    private static void EmitMatrixIntRaw(StringBuilder sb, string name, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
    {
        sb.Append("    public static readonly int[,] ").Append(name).Append(" = new int[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }
}
