using System.Collections.Generic;
using System.Text;
using AstFirst.Core.Parsing;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel からパーサの C# コードを生成する。
/// LalrTable (ACTION/GOTO) と Productions を static 配列に直列化し、
/// shift/reduce/accept を駆動する。Lexer の TokenId と文法の終端 Id は
/// Pattern で結んでマップする。reduce 時の AST 構築 (コンストラクタ呼び出し) は
/// フェーズ (4) で差し替えるため、ここではスタブ値を積む。
/// </summary>
public static class ParserEmitter
{
    public static string EmitParser(GrammarModel model, string ns)
    {
        var (grammar, table) = ModelToTable.BuildWithGrammar(model);
        var dfa = ModelToDfa.Build(model, out var rules);

        int stateCount = table.StateCount;
        int symbolCount = table.SymbolCount;
        int prodCount = grammar.Productions.Count;
        var (typeName, lexerName, parserName) = Names(model);

        // 終端 Symbol.Id (Pattern 列挙) と LexerRule.TokenId (Pattern 列挙) を突き合わせ。
        var patternToTerminalId = new Dictionary<string, int>();
        foreach (var sym in grammar.Symbols)
        {
            if (!sym.IsTerminal) continue;
            if (sym.Name.StartsWith("token:"))
                patternToTerminalId[sym.Name.Substring("token:".Length)] = sym.Id;
        }
        // tokenId -> terminal Symbol.Id
        int maxTokenId = 0;
        foreach (var r in rules) if (r.TokenId > maxTokenId) maxTokenId = r.TokenId;
        var tokenIdToSym = new int[maxTokenId + 1]; // 1..maxTokenId を使用
        for (int i = 0; i < tokenIdToSym.Length; i++) tokenIdToSym[i] = -1;
        foreach (var r in rules)
        {
            if (patternToTerminalId.TryGetValue(r.Pattern, out var sid))
                tokenIdToSym[r.TokenId] = sid;
        }

        int eofSym = grammar.EndOfFile.Id;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstFirst.Core.Lexing;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("public static class " + parserName);
        sb.AppendLine("{");

        // ActionKind / ActionValue
        EmitMatrixByte(sb, "ActionKind", table, stateCount, symbolCount, s => c => ActionKindByte(table.Action(s, c)));
        EmitMatrixInt(sb, "ActionValue", table, stateCount, symbolCount, s => c => table.Action(s, c).Value);
        EmitMatrixIntRaw(sb, "Goto", stateCount, symbolCount, s => c => table.Goto(s, c));

        // Productions: LHS と右辺長さ
        sb.Append("    public static readonly int[] ProdLhs = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Lhs.Id); }
        sb.AppendLine(" };");
        sb.Append("    public static readonly int[] ProdLen = new int[] { ");
        for (int p = 0; p < prodCount; p++) { if (p > 0) sb.Append(", "); sb.Append(grammar.Productions[p].Rhs.Length); }
        sb.AppendLine(" };");

        // TokenIdToSym
        sb.Append("    public static readonly int[] TokenIdToSym = new int[] { ");
        for (int i = 0; i < tokenIdToSym.Length; i++) { if (i > 0) sb.Append(", "); sb.Append(tokenIdToSym[i]); }
        sb.AppendLine(" };");

        sb.AppendLine("    public const int EofSym = " + eofSym + ";");
        sb.AppendLine("    public const int StateCount = " + stateCount + ";");
        sb.AppendLine("    public const int SymbolCount = " + symbolCount + ";");

        // SymNames[symbolId]: 記号名 (エラーメッセージ用)
        sb.Append("    public static readonly string?[] SymNames = new string?[] { ");
        for (int si = 0; si < symbolCount; si++)
        {
            if (si > 0) sb.Append(", ");
            var escaped = grammar.Symbols[si].Name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.Append("\"").Append(escaped).Append("\"");
        }
        sb.AppendLine(" };");

        // DefaultReduce[state]: デフォルト reduce (productionId、-1=なし)
        var dr = table.DefaultReduceTable;
        sb.Append("    public static readonly int[] DefaultReduce = new int[] { ");
        for (int s = 0; s < stateCount; s++) { if (s > 0) sb.Append(", "); sb.Append(s < dr.Count ? dr[s] : -1); }
        sb.AppendLine(" };");

        // [Context] を使う規則があれば BasicSemanticContext を用意。
        bool needsContext = false;
        for (int pi = 0; pi < grammar.Productions.Count; pi++)
            if (grammar.Productions[pi].Tag is ReduceActionModel am && am.Parameters.Any(p => p.IsContext))
                { needsContext = true; break; }

        // Parse
        sb.AppendLine("    public static AstFirst.ParseResult Parse(string input)");
        sb.AppendLine("    {");
        if (needsContext)
            sb.AppendLine("        var ctx = new AstFirst.BasicSemanticContext();");
        sb.AppendLine("        var tokens = " + lexerName + ".Tokenize(input);");
        sb.AppendLine("        var states = new Stack<int>();");
        sb.AppendLine("        var values = new Stack<object?>();");
        sb.AppendLine("        var errors = new System.Collections.Generic.List<AstFirst.ParseError>();");
        sb.AppendLine("        object? result = null;");
        sb.AppendLine("        states.Push(0);");
        sb.AppendLine("        int i = 0;");
        sb.AppendLine("        int lastErrorPos = -10; // 近接エラー抑制用");
        sb.AppendLine("        while (true)");
        sb.AppendLine("        {");
        sb.AppendLine("            int state = states.Peek();");
        sb.AppendLine("            int sym = (i < tokens.Count) ? TokenIdToSym[tokens[i].TokenId] : EofSym;");
        sb.AppendLine("            if (sym < 0) { errors.Add(new AstFirst.ParseError(\"未知のトークンです\", tokens[i].Start)); i++; continue; }");
        sb.AppendLine("            byte kind = ActionKind[state, sym];");
        sb.AppendLine("            int val = ActionValue[state, sym];");
        sb.AppendLine("            if (kind == 1) // Shift");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Push(sym == EofSym ? null : (object)ToToken(tokens[i]));");
        sb.AppendLine("                states.Push(val);");
        sb.AppendLine("                i++;");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (kind == 2 || (kind == 0 && DefaultReduce[state] >= 0)) // Reduce (通常 or デフォルト)");
        sb.AppendLine("            {");
        sb.AppendLine("                int prodId = (kind == 2) ? val : DefaultReduce[state];");
        sb.AppendLine("                var node = ReduceNode(prodId, values, states" + (needsContext ? ", ctx" : ", null") + ");");
        sb.AppendLine("                values.Push(node);");
        sb.AppendLine("                states.Push(Goto[states.Peek(), ProdLhs[prodId]]);");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (kind == 3) // Accept");
        sb.AppendLine("            {");
        sb.AppendLine("                values.Pop(); // $ を捨てる");
        sb.AppendLine("                result = values.Peek();");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
        sb.AppendLine("            else // Error: panic mode");
        sb.AppendLine("            {");
        sb.AppendLine("                int pos = i < tokens.Count ? tokens[i].Start : (tokens.Count > 0 ? tokens[tokens.Count - 1].End : 0);");
        sb.AppendLine("                // 近接エラー抑制 (3トークン以内は新エラーを抑止)");
        sb.AppendLine("                if (i - lastErrorPos >= 3)");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 期待トークンを計算");
        sb.AppendLine("                    var exp = new System.Text.StringBuilder();");
        sb.AppendLine("                    for (int e = 0; e < SymbolCount; e++)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        if (ActionKind[state, e] == 0) continue;");
        sb.AppendLine("                        if (exp.Length > 0) exp.Append(\", \");");
        sb.AppendLine("                        exp.Append(e == EofSym ? \"EOF\" : e < SymNames.Length ? SymNames[e] : \"#\" + e);");
        sb.AppendLine("                    }");
        sb.AppendLine("                    errors.Add(new AstFirst.ParseError(\"予期しないトークン\" + (exp.Length > 0 ? \" (期待: \" + exp + \")\" : \"\"), pos));");
        sb.AppendLine("                    lastErrorPos = i;");
        sb.AppendLine("                }");
        sb.AppendLine("                // スタックを戻して shift 可能な状態を探す");
        sb.AppendLine("                bool recovered = false;");
        sb.AppendLine("                while (states.Count > 1 && i < tokens.Count)");
        sb.AppendLine("                {");
        sb.AppendLine("                    states.Pop(); values.Pop();");
        sb.AppendLine("                    int topState = states.Peek();");
        sb.AppendLine("                    int curSym = TokenIdToSym[tokens[i].TokenId];");
        sb.AppendLine("                    if (curSym >= 0 && ActionKind[topState, curSym] != 0) { recovered = true; break; }");
        sb.AppendLine("                }");
        sb.AppendLine("                if (!recovered)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (states.Count <= 1) { while (states.Count > 0) states.Pop(); while (values.Count > 0) values.Pop(); states.Push(0); }");
        sb.AppendLine("                    if (i < tokens.Count) i++; else break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return new AstFirst.ParseResult(result, errors);");
        sb.AppendLine("    }");

        sb.AppendLine("    private static T[] PopN<T>(Stack<T> s, int n)");
        sb.AppendLine("    {");
        sb.AppendLine("        var a = new T[n];");
        sb.AppendLine("        for (int i = 0; i < n; i++) a[n - 1 - i] = s.Pop();");
        sb.AppendLine("        return a;");
        sb.AppendLine("    }");

        // ReduceNode: 規則 prodId で reduce。PopN + new AST_TYPE(args)。
        sb.AppendLine("    private static object? ReduceNode(int val, Stack<object?> values, Stack<int> states, AstFirst.SemanticContext? ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (val)");
        sb.AppendLine("        {");
        for (int pi = 0; pi < grammar.Productions.Count; pi++)
        {
            var prod = grammar.Productions[pi];
            if (prod.Tag is not ReduceActionModel action) continue;
            sb.Append("            case ").Append(prod.Id).Append(": { var c = PopN(values, ").Append(prod.Rhs.Length).Append("); PopN(states, ").Append(prod.Rhs.Length).Append("); return new ").Append(action.AstTypeName).Append("(");
            for (int j = 0; j < action.Parameters.Count; j++)
            {
                if (j > 0) sb.Append(", ");
                var p = action.Parameters[j];
                if (p.IsContext) sb.Append("ctx");
                else sb.Append("(").Append(p.CastTypeName).Append(")c[").Append(p.ChildIndex).Append("]");
            }
            sb.AppendLine("); }");
        }
        sb.AppendLine("            default: { PopN(values, ProdLen[val]); PopN(states, ProdLen[val]); return null; }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static AstFirst.Token ToToken(AstFirst.Core.Lexing.LexToken t)");
        sb.AppendLine("        => new AstFirst.BasicToken(t.Text, new AstFirst.SourceSpan(new AstFirst.Position(t.Start, 0, 0), new AstFirst.Position(t.End, 0, 0)));");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static byte ActionKindByte(LrAction a) => a.Kind switch
    {
        LrActionKind.Shift => 1,
        LrActionKind.Reduce => 2,
        LrActionKind.Accept => 3,
        _ => 0
    };

    private static (string type, string lexer, string parser) Names(GrammarModel model)
    {
        var (ns, type) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        var suffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
        return (type + suffix, type + suffix + "Lexer", type + suffix + "Parser");
    }

    private static void EmitMatrixByte(StringBuilder sb, string name, LalrTable _, int rows, int cols,
        System.Func<int, System.Func<int, byte>> cell)
    {
        sb.Append("    public static readonly byte[,] ").Append(name).Append(" = new byte[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }

    private static void EmitMatrixInt(StringBuilder sb, string name, LalrTable _, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
        => EmitMatrixIntRaw(sb, name, rows, cols, s => cell(s));

    private static void EmitMatrixIntRaw(StringBuilder sb, string name, int rows, int cols,
        System.Func<int, System.Func<int, int>> cell)
    {
        sb.Append("    public static readonly int[,] ").Append(name).Append(" = new int[").Append(rows).Append(", ").Append(cols).AppendLine("]");
        sb.AppendLine("    {");
        for (int r = 0; r < rows; r++)
        {
            var row = cell(r);
            sb.Append("        { ");
            for (int c = 0; c < cols; c++) { if (c > 0) sb.Append(", "); sb.Append(row(c)); }
            sb.Append(" }");
            sb.AppendLine(r < rows - 1 ? "," : "");
        }
        sb.AppendLine("    };");
    }
}
