using System.Linq;
using System.Text;

namespace AstFirst.Generator;

/// <summary>
/// GrammarModel から汎用 AST Walker を生成する。
/// 反復スタックで Enter→子→Exit を駆動し、各具象ノードの EnterXxx/ExitXxx と
/// IOnSecondPassEnter/Exit・[Enter]/[Exit] 属性メソッドの呼び出しを行う。
/// ユーザーは継承して EnterXxx/ExitXxx を override し、Walk(ルート, ctx) を呼んで意味解析や独自の AST 走査を行う。
/// </summary>
/// <remarks>
/// Parser の Parse() 末尾で既定インスタンス (<c>_Default</c>) を介して自動駆動される。
/// IOnSecondPassEnter/Exit・[Enter]/[Exit]・EnterXxx/ExitXxx override がない場合は実質 no-op。
/// </remarks>
public static class WalkerEmitter
{
    public static string EmitWalker(GrammarModel model, string ns)
    {
        var (_, rootType) = CodeEmitter.SplitFullName(model.RootTypeFullName);
        var suffix = string.IsNullOrEmpty(model.Mode) ? "" : "_" + model.Mode;
        var walkerName = rootType + suffix + "Walker";

        var concrete = model.Nodes.Where(n => !n.IsAbstract).ToList();
        var enterRules = model.AnalyzeRules.Where(r => r.Phase == AnalyzePhase.Enter).ToList();
        var exitRules = model.AnalyzeRules.Where(r => r.Phase == AnalyzePhase.Exit).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using AstFirst;");
        sb.AppendLine("using System.Collections.Generic;");
        if (ns.Length > 0) { sb.AppendLine("namespace " + ns + ";"); sb.AppendLine(); }
        sb.AppendLine("/// <summary>汎用 AST Walker。Walk で Enter→子→Exit を駆動。EnterXxx/ExitXxx を override して使う。</summary>");
        sb.AppendLine("public abstract class " + walkerName);
        sb.AppendLine("{");

        // Walk: 反復スタック。EnterEach → 子(逆順push) → ExitEach。
        sb.AppendLine("    /// <summary>AST をトップダウンで訪問します: EnterEach → 子 → ExitEach。反復的実装 (深い/広い AST でもスタックオーバーフローしない)。</summary>");
        sb.AppendLine("    public void Walk(AstFirst.AstNode root, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (root is null) return;");
        sb.AppendLine("        var stack = new Stack<(AstFirst.AstNode node, bool isExit)>();");
        sb.AppendLine("        stack.Push((root, false));");
        sb.AppendLine("        while (stack.Count > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            var (node, isExit) = stack.Pop();");
        sb.AppendLine("            if (isExit)");
        sb.AppendLine("            {");
        sb.AppendLine("                ExitEach(node, ctx);");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine("            EnterEach(node, ctx);");
        sb.AppendLine("            stack.Push((node, true)); // Exit 用");
        sb.AppendLine("            var children = GetChildren(node);");
        sb.AppendLine("            for (int i = children.Count - 1; i >= 0; i--) stack.Push((children[i], false));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EnterEach: IOnSecondPassEnter → [Enter] static → EnterXxx virtual
        sb.AppendLine("    /// <summary>ノードに入る時の処理。IOnSecondPassEnter・[Enter] 属性メソッド・EnterXxx を呼ぶ。override して拡張可。</summary>");
        sb.AppendLine("    protected virtual void EnterEach(AstFirst.AstNode node, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (node is AstFirst.IOnSecondPassEnter en) en.OnSecondPassEnter(ctx);");
        EmitAnalyzeDispatch(sb, enterRules);
        if (concrete.Count > 0)
        {
            sb.AppendLine("        switch (node)");
            sb.AppendLine("        {");
            foreach (var n in concrete)
                sb.Append("            case ").Append(n.FullName).Append(" n: Enter").Append(SimpleName(n.FullName)).AppendLine("(n, ctx); break;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // ExitEach: ExitXxx virtual → [Exit] static → IOnSecondPassExit
        sb.AppendLine("    /// <summary>ノードを出る時の処理。ExitXxx・[Exit] 属性メソッド・IOnSecondPassExit を呼ぶ。override して拡張可。</summary>");
        sb.AppendLine("    protected virtual void ExitEach(AstFirst.AstNode node, AstFirst.SemanticContext ctx)");
        sb.AppendLine("    {");
        if (concrete.Count > 0)
        {
            sb.AppendLine("        switch (node)");
            sb.AppendLine("        {");
            foreach (var n in concrete)
                sb.Append("            case ").Append(n.FullName).Append(" n: Exit").Append(SimpleName(n.FullName)).AppendLine("(n, ctx); break;");
            sb.AppendLine("        }");
        }
        EmitAnalyzeDispatch(sb, exitRules);
        sb.AppendLine("        if (node is AstFirst.IOnSecondPassExit ex) ex.OnSecondPassExit(ctx);");
        sb.AppendLine("    }");

        // EnterXxx / ExitXxx (具象ノード毎)
        foreach (var n in concrete)
        {
            var sn = SimpleName(n.FullName);
            sb.AppendLine();
            sb.AppendLine("    /// <summary>" + sn + " ノードに入る時に呼ばれます。オーバーライドして処理します。</summary>");
            sb.AppendLine("    protected virtual void Enter" + sn + "(" + n.FullName + " node, AstFirst.SemanticContext ctx) { }");
            sb.AppendLine("    /// <summary>" + sn + " ノードを出る時に呼ばれます。オーバーライドして処理します。</summary>");
            sb.AppendLine("    protected virtual void Exit" + sn + "(" + n.FullName + " node, AstFirst.SemanticContext ctx) { }");
        }

        // GetChildren: private static
        sb.AppendLine();
        sb.AppendLine("    private static List<AstFirst.AstNode> GetChildren(AstFirst.AstNode node)");
        sb.AppendLine("    {");
        sb.AppendLine("        var children = new List<AstFirst.AstNode>();");
        sb.AppendLine("        switch (node)");
        sb.AppendLine("        {");
        foreach (var n in model.Nodes)
        {
            if (n.IsAbstract) continue;
            sb.AppendLine("            case " + n.FullName + " __n:");
            foreach (var c in n.Children)
            {
                if (c.IsRepeat)
                    sb.AppendLine("                foreach (var __c in __n." + c.PropertyName + ") children.Add(__c);");
                else if (c.IsNullable)
                    sb.AppendLine("                if (__n." + c.PropertyName + " is not null) children.Add(__n." + c.PropertyName + ");");
                else
                    sb.AppendLine("                children.Add(__n." + c.PropertyName + ");");
            }
            sb.AppendLine("                break;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        return children;");
        sb.AppendLine("    }");

        // _Default: Parser が既定で使うネスト Walker インスタンス
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Parser が Parse() で既定駆動する Walker (何も override しない)。</summary>");
        sb.AppendLine("    internal sealed class _Default : " + walkerName + " { }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>[Enter]/[Exit] 属性メソッドの型 switch dispatch を生成。対象ノード型ごとにグループ化して case を出す。</summary>
    private static void EmitAnalyzeDispatch(StringBuilder sb, System.Collections.Generic.List<AnalyzeRuleModel> rules)
    {
        if (rules.Count == 0) return;
        sb.AppendLine("        switch (node)");
        sb.AppendLine("        {");
        foreach (var grp in rules.GroupBy(r => r.TargetNodeFullName))
        {
            sb.Append("            case ").Append(grp.Key).AppendLine(" n:");
            sb.AppendLine("            {");
            foreach (var r in grp)
                sb.AppendLine("                " + r.GrammarClassFullName + "." + r.MethodName + "(n, (" + r.CtxTypeFullName + ")ctx);");
            sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");
    }

    private static string SimpleName(string fullName)
    {
        var idx = fullName.LastIndexOf('.');
        return idx < 0 ? fullName : fullName.Substring(idx + 1);
    }
}
