// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfDeepNest;

[Grammar]
[Skip(@"\s+")]
public abstract class NestExpr : AstNode { }

public sealed class NumExpr : NestExpr
{
    public NumExpr([Pattern(@"[0-9]+")] Token num) { }
}

public sealed class ParenExpr : NestExpr
{
    public ParenExpr([Pattern(@"\(")] Token lp, NestExpr inner, [Pattern(@"\)")] Token rp) { }
}

