// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfDeepNest;

[Grammar]
[Skip(@"\s+")]
public abstract partial class NestExpr : AstNode { }

public sealed partial class NumExpr : NestExpr
{
    [Rule]
    public static void Reduce([Pattern(@"[0-9]+")] Token num) { }
}

public sealed partial class ParenExpr : NestExpr
{
    [Rule]
    public static void Reduce([Pattern(@"\(")] Token lp, NestExpr inner, [Pattern(@"\)")] Token rp) { }
}

