// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>
using AstFirst;

namespace PerfWideRules;

[Grammar]
[Skip(@"\s+")]
public abstract partial class WideProgram : AstNode { }

public sealed partial class ConsStmt : WideProgram
{
    [Rule]
    public static void Reduce(Stmt first, WideProgram rest) { }
}

public sealed partial class NilProgram : WideProgram
{
    [Rule]
    public static void Reduce() { }
}

public abstract partial class Stmt : AstNode { }

public sealed partial class Stmt0 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s0")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt1 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s1")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt2 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s2")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt3 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s3")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt4 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s4")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt5 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s5")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt6 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s6")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt7 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s7")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt8 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s8")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt9 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s9")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt10 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s10")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt11 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s11")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt12 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s12")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt13 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s13")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt14 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s14")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt15 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s15")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt16 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s16")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt17 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s17")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt18 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s18")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt19 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s19")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt20 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s20")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt21 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s21")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt22 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s22")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt23 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s23")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt24 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s24")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt25 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s25")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt26 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s26")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt27 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s27")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt28 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s28")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt29 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s29")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt30 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s30")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt31 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s31")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt32 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s32")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt33 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s33")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt34 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s34")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt35 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s35")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt36 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s36")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt37 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s37")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt38 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s38")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt39 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s39")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt40 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s40")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt41 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s41")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt42 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s42")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt43 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s43")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt44 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s44")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt45 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s45")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt46 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s46")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt47 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s47")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt48 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s48")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt49 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s49")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt50 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s50")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt51 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s51")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt52 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s52")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt53 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s53")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt54 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s54")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt55 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s55")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt56 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s56")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt57 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s57")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt58 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s58")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt59 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s59")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt60 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s60")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt61 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s61")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt62 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s62")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt63 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s63")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt64 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s64")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt65 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s65")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt66 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s66")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt67 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s67")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt68 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s68")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt69 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s69")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt70 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s70")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt71 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s71")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt72 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s72")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt73 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s73")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt74 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s74")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt75 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s75")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt76 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s76")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt77 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s77")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt78 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s78")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt79 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s79")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt80 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s80")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt81 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s81")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt82 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s82")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt83 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s83")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt84 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s84")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt85 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s85")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt86 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s86")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt87 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s87")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt88 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s88")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt89 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s89")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt90 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s90")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt91 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s91")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt92 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s92")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt93 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s93")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt94 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s94")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt95 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s95")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt96 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s96")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt97 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s97")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt98 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s98")] Token kw, [Pattern(@";")] Token semi) { }
}

public sealed partial class Stmt99 : Stmt
{
    [Rule]
    public static void Reduce([Pattern(@"s99")] Token kw, [Pattern(@";")] Token semi) { }
}

