using System.Text;
using AstFirst.Core.Parsing;
using AstFirst.Generator;

namespace Perf.Grammars;

/// <summary>
/// 1つの文法パターンの中間仕様。1つの仕様から、コンパイルされる C# ソース (csSource) と、
/// Generator が .cs から抽出するのと等価な <see cref="GrammarModel"/> (POCO) を整合的に導出する。
/// これにより「文法プロジェクトがビルドする文法」と「Perf.Bench がテーブル構築計測に使う
/// GrammarModel」が常に一致する。
/// </summary>
public sealed class GrammarSpec
{
    public string Namespace { get; }
    public string RootClass { get; }
    /// <summary>csSource の [Skip(@"...")] に埋め込む正規表現 (verbatim 内なのでそのまま)。</summary>
    public string SkipRegex { get; }
    public List<NodeSpec> Nodes { get; } = new();

    public GrammarSpec(string ns, string rootClass, string skipRegex)
    {
        Namespace = ns;
        RootClass = rootClass;
        SkipRegex = skipRegex;
    }

    public NodeSpec AddAbstract(string className, string baseClass)
    {
        var n = new NodeSpec(className, baseClass, isAbstract: true, precedence: 0, isRightAssoc: false);
        Nodes.Add(n);
        return n;
    }

    public NodeSpec AddSealed(string className, string baseClass, int precedence = 0, bool isRightAssoc = false)
    {
        var n = new NodeSpec(className, baseClass, isAbstract: false, precedence, isRightAssoc);
        Nodes.Add(n);
        return n;
    }

    /// <summary>コンパイルされる C# 文法ソースを生成。Generator がこれを読んで Parser を生成する。</summary>
    public string ToCsSource()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Perf.Grammars — 大規模文法ベンチマーク用。編集しないこと。/>");
        sb.AppendLine("using AstFirst;");
        sb.AppendLine();
        sb.AppendLine("namespace " + Namespace + ";");
        sb.AppendLine();

        // ルート (開始記号)
        sb.AppendLine("[Grammar]");
        sb.AppendLine("[Skip(@\"" + SkipRegex + "\")]");
        sb.AppendLine("public abstract class " + RootClass + " : AstNode { }");
        sb.AppendLine();

        foreach (var n in Nodes)
        {
            if (n.ClassName == RootClass) continue; // ルートは上で出力済み
            if (n.IsAbstract)
            {
                sb.AppendLine("public abstract class " + n.ClassName + " : " + n.BaseClass + " { }");
                sb.AppendLine();
                continue;
            }

            if (n.Precedence > 0)
            {
                var p = "[Precedence(" + n.Precedence;
                if (n.IsRightAssoc) p += ", IsRightAssociative = true";
                p += ")]";
                sb.AppendLine(p);
            }
            sb.AppendLine("public sealed class " + n.ClassName + " : " + n.BaseClass);
            sb.AppendLine("{");
            foreach (var ctor in n.Ctors)
            {
                var ps = new List<string>();
                foreach (var p in ctor)
                {
                    var attr = "";
                    if (p.Pattern is not null)
                    {
                        attr = "[Pattern(@\"" + p.Pattern + "\"";
                        if (p.Priority != 0) attr += ", Priority = " + p.Priority;
                        attr += ")] ";
                    }
                    ps.Add(attr + p.CsType + " " + p.Name);
                }
                sb.AppendLine("    public " + n.ClassName + "(" + string.Join(", ", ps) + ") { }");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>Generator が抽出するのと等価な GrammarModel を構築。Perf.Bench のテーブル構築計測に使う。</summary>
    public GrammarModel ToModel()
    {
        var nodes = new List<NodeModel>();
        var tokenDefs = new List<TokenDefModel>();

        foreach (var n in Nodes)
        {
            var baseFullName = n.BaseClass == "AstNode" ? "AstFirst.AstNode" : Namespace + "." + n.BaseClass;
            var ctors = new List<CtorModel>();
            if (!n.IsAbstract)
            {
                foreach (var ctor in n.Ctors)
                {
                    var ps = new List<ParamModel>();
                    foreach (var p in ctor)
                    {
                        if (p.Pattern is not null)
                        {
                            // Token 型の終端 ([Pattern] 付き)。
                            ps.Add(new ParamModel("AstFirst.Token", p.Name, p.Pattern, isContext: false, p.Priority, ToAssoc(p)));
                            tokenDefs.Add(new TokenDefModel("AstFirst.Token", p.Pattern, p.Priority, isHidden: false));
                        }
                        else
                        {
                            // 非終端 (AstNode 派生クラス)。
                            ps.Add(new ParamModel(Namespace + "." + p.CsType, p.Name, pattern: null, isContext: false, priority: 0, associativity: Associativity.Left));
                        }
                    }
                    ctors.Add(new CtorModel(ps));
                }
            }
            nodes.Add(new NodeModel(
                Namespace + "." + n.ClassName, baseFullName, n.IsAbstract, ctors,
                children: System.Array.Empty<ChildModel>(),
                precedencePriority: n.Precedence,
                precedenceAssoc: n.IsRightAssoc ? Associativity.Right : Associativity.Left));
        }

        // ModelExtraction と同じ順序 (FullName 昇順) に。テーブル構築は非順序依存だが整合性のため。
        nodes.Sort((a, b) => string.CompareOrdinal(a.FullName, b.FullName));

        // TokenDefs を (Key, Pattern) で重複除去し、Key → Pattern の順でソート (ModelExtraction.Dedup 互換)。
        var dedupDefs = tokenDefs
            .GroupBy(d => (d.Key, d.Pattern))
            .Select(g => g.First())
            .OrderBy(d => d.Key)
            .ThenBy(d => d.Pattern)
            .ToList();

        var skipPatterns = new List<string> { SkipRegex };
        return new GrammarModel(Namespace + "." + RootClass, nodes, dedupDefs, skipPatterns, mode: null);
    }

    private static Associativity ToAssoc(ParamSpec p)
        => p.IsNonAssoc ? Associativity.NonAssoc : p.IsRightAssoc ? Associativity.Right : Associativity.Left;
}

public sealed class NodeSpec
{
    public string ClassName { get; }
    public string BaseClass { get; }
    public bool IsAbstract { get; }
    public int Precedence { get; }
    public bool IsRightAssoc { get; }
    public List<List<ParamSpec>> Ctors { get; } = new();

    public NodeSpec(string className, string baseClass, bool isAbstract, int precedence, bool isRightAssoc)
    {
        ClassName = className;
        BaseClass = baseClass;
        IsAbstract = isAbstract;
        Precedence = precedence;
        IsRightAssoc = isRightAssoc;
    }

    /// <summary>コンストラクタ (= 生成規則) を追加。fluent。</summary>
    public NodeSpec Ctor(params ParamSpec[] ps)
    {
        Ctors.Add(ps.ToList());
        return this;
    }
}

/// <summary>コンストラクタ引数。Pattern != null なら [Pattern] 付き終端 (Token 型)。</summary>
public sealed class ParamSpec
{
    public string CsType { get; }       // C# 型名 (csSource 用): "Token" または AST クラス名
    public string Name { get; }
    public string? Pattern { get; }     // [Pattern] の正規表現 (csSource の @"..." に埋め込む)。null = 非終端
    public int Priority { get; }
    public bool IsRightAssoc { get; }
    public bool IsNonAssoc { get; }

    public ParamSpec(string csType, string name, string? pattern = null, int priority = 0,
        bool isRightAssoc = false, bool isNonAssoc = false)
    {
        CsType = csType;
        Name = name;
        Pattern = pattern;
        Priority = priority;
        IsRightAssoc = isRightAssoc;
        IsNonAssoc = isNonAssoc;
    }
}
